- backend/build.gradle
- backend/src/main/java/com/votogether/VotogetherApplication.java
- backend/src/main/java/com/votogether/config/JpaConfig.java
- backend/src/main/java/com/votogether/config/OpenAPIConfig.java
- backend/src/main/java/com/votogether/domain/common/BaseEntity.java
- backend/src/main/java/com/votogether/domain/healthcheck/controller/HealthCheckController.java
- backend/src/main/java/com/votogether/domain/healthcheck/service/HealthCheckService.java
- backend/src/main/java/com/votogether/domain/post/entity/Post.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/votogether/VotogetherApplicationTests.java
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/ProgressBar/ProgressBar.stories.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/ProgressBar/index.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/ProgressBar/style.ts
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/WrittenVoteOption.stories.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/style.ts
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOptionList.stories.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/index.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/style.ts
close: #18 
- 게시글에서 보는 투표 선택지 컴포넌트 UI 구현
- 백앤드에서 보내주는 데이터 위주를 생각하여 props 구현
- 옵션 리스트 컴포넌트의 선택된 옵션 ID를 통해 하위 옵션 컴포넌트의 스타일(투표여부, 선택여부 등) 변화
- 옵션 리스트 컴포넌트에 투표 선택지 아이디를 매개 변수로 하는 투표 선택지 클릭 이벤트를 프롭스 전달 
- 옵션 컴포넌트: 홈 화면(내용 일부 공개)과 상세 페이지 화면(내용 내용 공개) 구분
```tsx
interface ProgressBarProps {
percent: number; // 몇 퍼센트인지
isSelected: boolean; // 내가 선택한 선택지인지
}
```
```tsx
interface WrittenVoteOptionProps {
handleVoteClick: () => void; // 투표를 선택하는 클릭 이벤트
text: string; // 선택지 내용
isVoted: boolean; // 사용자가 해당 게시글 선택지에 투표했는지 여부
peopleCount: number; // 선택지를 선택한 사용자 수
percent: number; // 선택지를 선택한 사용자 퍼센트
isSelected: boolean; // 선택지를 본인이 선택하였는 지 여부
isPreview: boolean; //  isPreview:  true일 때 글 목록에서 선택지 내용을 2줄 생략으로 보여줌 , false일 때 글 상세 페이지에서 선택지 내용을 전부 보여줌
imageUrl?: string; // 선택지의 이미지 소스
}
```
```tsx …
```
> 게시글에서 보는 투표 선택지 컴포넌트 UI 구현

- frontend/.env
- frontend/.gitignore
- frontend/.storybook/main.ts
- frontend/.storybook/preview.tsx
- frontend/.storybook/public/mockServiceWorker.js
- frontend/.storybook/webpack.config.js
- frontend/package-lock.json
- frontend/package.json
- frontend/public/mockServiceWorker.js
- frontend/src/App.tsx
- frontend/src/index.tsx
- frontend/src/mocks/example/get.ts
- frontend/src/mocks/handlers.ts
- frontend/src/mocks/worker.ts
- frontend/webpack.common.js
close: #46
<br>
- msw 설치
- 스토리북에도 적용
- react-query 설치
- 스토리북에도 적용
-.env 설정
- 스토리북에도 적용
<br>
- msw mocking 추가시 예제파일 확인 필요
<br>
없습니다.
> 리액트 쿼리, msw 설치 및 셋팅

- frontend/src/components/common/Modal/Modal.stories.tsx
- frontend/src/components/common/TimePickerOptionList/TimePickerOption/TimePickerOption.stories.tsx
- frontend/src/components/common/TimePickerOptionList/TimePickerOption/constants.ts
- frontend/src/components/common/TimePickerOptionList/TimePickerOption/index.tsx
- frontend/src/components/common/TimePickerOptionList/TimePickerOptionList.stories.tsx
- frontend/src/components/common/TimePickerOptionList/index.tsx
- frontend/src/components/common/TimePickerOptionList/style.ts
안녕하세요 여러분~ 벌써 한 주가 지났네요😮👏👏
이번 주에 개발하느라 리뷰하느라 고생 많으셨습니다..🥺
close: #34 
* day, hour, minute 3개의 상태를, time 이라는 객체로서 하나의 상태로 통합함.
* Modal 컴포넌트의 story로 WithTimePicker 추가
* 처음에는 TimePickerModal 컴포넌트를 별도로 만들려고 했었지만, 
* 재사용될 여지가 없다면 불필요하게 컴포넌트를 만들지 않는 것이 낫다고 판단하여,  
* Modal 컴포넌트의 story(With Time Picker)를 통해 `마감시간을 선택하는 모달`의 UI와 동작을 보여주는 방식으로 대체하였습니다!  
* 더불어 원래는 day, hour, minute 이라는 3개의 상태가 각각 있었으나, 
* time 이라는 객체 하나로 상태 관리하도록 리팩터링하였습니다.
* 원래 피그마 시안에서는 저장 버튼이 있었습니다! 
* 그런데 만들면서 생각해보니, 모달에서 꼭 저장 버튼을 눌러야 마감 시간이 업데이트되게 하는 것이... 사용자 관점에서 편리한지 잘 모르겠더라구요..? 
* 그래서 스크롤로 세팅하면 바로 상태(time 객체 state)가 바뀌게 했습니다! (저장 버튼 클릭 같은 동작이 따로 없어도 상태가 업데이트됨)
---
항상 구구절절 질문 많고 설명 많은데 친절히 코멘트 남겨주셔서 감사합니다^.^ 여러분이 짱이에요😄😄😉👍
> TimePicker Modal 구현

- frontend/src/components/common/Skeleton/Skeleton.stories.tsx
- frontend/src/components/common/Skeleton/index.tsx
- frontend/src/components/common/Skeleton/style.ts
close: #59 
20분
📦Skeleton
┣ 📜Skeleton.stories.tsx
┣ 📜index.tsx
┗ 📜style.ts
스켈레톤 UI 구현
- 모바일 기준으로 반응형에 따라 다르게 보여주도록 했습니다.
- 애니메이션을 주었습니다. (애니메이션 참고 자료 : https://velog.io/@eunoia/PureCSS%EB%A1%9C-Skeleton-%EC%A0%9C%EC%9E%91%ED%95%98%EA%B8%B0)
- <a href="https://uxdesign.cc/what-you-should-know-about-skeleton-screens-a820c45a571a">Bill Chung의 연구</a>에 따르면 스켈레톤 내 애니메이션을 규칙에 맞게 사용하면 사용자가 더 로딩 시간을 더 짧게 느끼게 된다고 합니다.
- 맥박보다는 웨이브 효과
- 왼쪽에서 오른쪽으로 움직이는 애니메이션
- 애니메이션은 Skeleton 컴포넌트에 주의를 끌만큼 빠르지 않아야 함
> 스켈레톤 UI 구현

- backend/src/main/java/com/votogether/domain/category/contorller/CategoryController.java
- backend/src/main/java/com/votogether/domain/category/dto/response/CategoryResponse.java
- backend/src/main/java/com/votogether/domain/category/entity/Category.java
- backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
- backend/src/test/java/com/votogether/domain/RepositoryTest.java
- backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
close: #50 
(비회원) 전체 카테고리 목록 조회 기능 구현
비회원 권한일때 전체 카테고리 목록을 조회하는 기능입니다.
이건 다행히 충돌 안나는 도메인인거같아요
> (비회원) 전체 카테고리 목록 조회 API 구현

- backend/src/main/java/com/votogether/config/WebMvcConfig.java
close: #100 

Cors origins, method 설정 전체 허용으로 변경
없음.
없음.
> CORS Origin 설정

- frontend/env.d.ts
- frontend/src/components/common/Dashboard/CategoryToggle/index.tsx
- frontend/src/components/common/Dashboard/CategoryToggle/style.ts
- frontend/src/components/common/Dashboard/UserProfile/index.tsx
- frontend/src/constants/path.ts
- frontend/src/routes/router.tsx
- frontend/tsconfig.json
close: #124 
.env의 타입을 적용해서 process.env. 하였을 때 자동 완성이 되도록 타입 적용
회의 때 바뀐 경로를 constants/path 및 router 파일에 적용
- 사이드바 카테고리 목록에서 경로 잘못되어 있는 부분 수정
- 사이드바 유저 작성 글, 투표한 글 경로 잘못되어 있는 부분 수정
- router 부분 리팩터링 하였습니다
- 아직 만들지 않은 페이지는 <Home/> 컴포넌트를 주었습니다.
- 수아와 작업이 겹치는 부분이 있는데 슬랙으로 이야기 하려고 합니다
> .env 파일 타입 선언 및 router 및 경로 설정

- backend/src/main/resources/application.yml
close: #143
리버스 프록시 헤더 설정을 추가하였습니다.
- nginx 설정 추가
- 스프링 부트 설정 추가
> Swagger 디폴트페이지 버그 해결

- frontend/src/components/PostForm/index.tsx
- frontend/src/components/PostForm/style.ts
- frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/style.ts
- frontend/src/components/optionList/WritingVoteOptionList/style.ts
close: #136 
- 웹 화면에서 저장 버튼이 보이고 기능하도록 수정
- 작성 글 페이지에서 버튼의 스타일을 변경
- 마감 시간 중 0인 값이 있다면 보이지 않도록 수정

선택지가 비어도 작성이 되거나, 마감 시간이 0이여도 작성이 되는 이슈가 있습니다
따로 이슈를 파서 진행해야 할 것 같아요
> 웹 화면에서 글 게시글 작성 저장 버튼이 보이도록 수정 및 스타일 수정

- backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
close: #189 
undefined 이미지 파일 디버깅을 위해 예외 스택 호출 코드 추가
undefined 이미지 파일 디버깅을 위해 예외 스택 호출 코드 추가
> undefined 이미지 파일 디버깅을 위해 예외 스택 호출 코드 추가

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
이미지 파일 받기 위해 파라미터 네임 지정
이미지 파일 받기 위해 파라미터 네임 지정
> 이미지 파일 받기 위해 파라미터 네임 지정

- backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
디버깅을 위한 예외 추적 코드 추가
디버깅을 위한 예외 추적 코드 추가
> 디버깅을 위한 예외 추적 코드 추가

- backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
이미지 파일 관련 에러 추적을 위한 코드 추가
이미지 파일 관련 에러 추적을 위한 코드 추가
> 이미지 파일 관련 에러 추적을 위한 코드 추가

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
에러 디버깅 관련 추적 코드 수정
에러 디버깅 관련 추적 코드 수정
> 에러 디버깅 관련 추적 코드 수정

- backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
close: #215 
반환되는 날짜 데이터의 형식 수정
반환되는 날짜 데이터의 형식 수정
> 반환되는 날짜 데이터의 형식 수정

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
close: #217 
requestPart의 name 속성 생략
requestPart의 name 속성 생략 및 출력 코드 변경
> requestPart의 name 속성 생략

- backend/src/main/java/com/votogether/domain/post/service/PostService.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
close: #224 
작성자가 아니면 예외 처리하는 로직 삭제
작성자가 아니면 예외 처리하는 로직 삭제
> 작성자가 아니면 예외 처리하는 로직 삭제

- backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
- backend/src/main/java/com/votogether/domain/post/util/ImageUploader.java
- backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
close: #228
이미지 디렉토리 경로를 수정하였습니다 :)
현재 이미지는 /images 경로에 저장되고 있습니다. 하지만 해당 경로는 프론트엔드에서 화면 경로로 보여줄 수 있는 여지가 있기에 앞에 prefix인 static을 붙이도록 수정하려고 합니다.
3차 데모데이 화이팅 🔥
> 이미지 디렉토리 경로 수정

- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
- frontend/src/pages/post/PostDetail/index.tsx
- frontend/src/utils/fetch.ts
close: #233 
* 글 상세 페이지에서 이미지가 깨지는 에러 해결
* 댓글 등록 fetch 함수에서 content type 수정
화이팅~
> 글 상세 페이지에서 이미지 url 수정 및 댓글 등록 fetch 함수 content type 수정

- frontend/src/components/comment/CommentList/CommentItem/index.tsx
- frontend/src/utils/fetch.ts
close: #236 
* 게시글 작성 시 content type 이 맞지 않아 작성이 되지 않음
* 댓글 수정 에러 해결 (props 값 변경)
> 게시글 작성 시 content type 수정 및 댓글 수정 에러 해결

- backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
close: #240
중복 카테고리 추가 시 예외 발생 수정
중복 카테고리 추가 시 예외 발생 수정
화이팅 :)
> 선호 카테고리 중복 추가 예외 수정

- backend/src/main/java/com/votogether/domain/post/entity/Post.java
- backend/src/main/java/com/votogether/domain/post/service/PostService.java
- backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
close: #245
조기 마감 제한을 삭제하였습니다.
조기 마감 제한이 있던 것을 우선 삭제하도록 수정하였습니다.
화이팅 :)
> 조기 마감 제한 제거

- backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
close: #
수행할 작업을 1~2줄 사이로 요약해주세요.
> 데모데이 운영서버 빌드 및 배포 시연

- backend/src/main/java/com/votogether/domain/member/entity/Member.java
- backend/src/main/java/com/votogether/domain/member/entity/Nickname.java
- backend/src/test/java/com/votogether/domain/member/entity/NicknameTest.java
close: #263 
초기 닉네임 생성 정책을 변경했습니다.
USER1 + RandomStringUtils를 사용해서 15글자의 바꾸고싶은 닉네임으로 지정했습니다.
> 초기 닉네임 생성 정책 변경

- frontend/src/components/common/SnackBar/SnackBar.stories.tsx
- frontend/src/components/common/SnackBar/index.tsx
- frontend/src/components/common/SnackBar/style.ts
- frontend/src/components/common/Toast/Toast.stories.tsx
- frontend/src/components/common/Toast/index.tsx
- frontend/src/components/common/Toast/style.ts
- frontend/src/components/common/ToastNSnackBarStyle.ts
- frontend/src/constants/animation.ts
- frontend/src/hooks/useToast.ts
close: #258
토스트/ 스낵바 컴포넌트 제작
- 토스트 컴포넌트
- 관련 훅 제작: 기존 토글은 닫는 것을 수동으로 해야 함. 이를 setTimeout으로 변경한 훅을 제작.
- 프롭스로 위치와 사이즈, 내부 텍스트를 받음
- size = sm / md / lg / free
- position: top / bottom
- 노출시간 상수화(지금은 3초)
- 추후 신고 등의 단순 안내 문구 출력시 사용 
- 스낵바 컴포넌트
- 토글 훅 사용. 일반적으로 닫기 버튼이 존재하기 때문에 외부에서 이 훅으로 닫기를 제어
- 프롭스로 위치와 사이즈, children node를 받음
- size = sm / md / lg / free
- position: top / bottom
- 스낵바는 안에 버튼이 몇 개 들어갈지 알 수 없고, 이에 따른 이벤트도 알 수 없어 string 이 아닌 node children을 받음
- 요청에 대한 취소/ 잘못된 요청에 대한 가이드 제시 등 인터렉션 유도할 때 사용
- 사용예시는 스토리북 참고
> 토스트/스낵바 컴포넌트 제작

- backend/src/main/java/com/votogether/domain/auth/dto/KakaoMemberResponse.java
- backend/src/main/java/com/votogether/domain/member/dto/MemberInfoResponse.java
- backend/src/main/java/com/votogether/domain/member/entity/AgeRange.java
- backend/src/main/java/com/votogether/domain/member/entity/Member.java
- backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
- backend/src/main/java/com/votogether/domain/post/dto/response/vote/VoteOptionStatisticsResponse.java
- backend/src/main/java/com/votogether/domain/post/service/PostService.java
- backend/src/main/java/com/votogether/domain/vote/dto/VoteStatus.java
- backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
- backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
- backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
- backend/src/test/java/com/votogether/domain/member/repository/MemberCategoryRepositoryTest.java
- backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
- backend/src/test/java/com/votogether/domain/report/controller/ReportControllerTest.java
- backend/src/test/java/com/votogether/domain/report/service/ReportServiceTest.java
- backend/src/test/java/com/votogether/domain/vote/repository/VoteRepositoryTest.java
- backend/src/test/java/com/votogether/fixtures/MemberFixtures.java
- backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
- backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
close: #323
Member 스키마 수정에 따른 코드를 변경하였습니다.
Member 스키마 수정에 따른 코드를 변경하였습니다.
모두들 수고하셨습니다 :)
> Member 스키마 수정에 따른 코드 변경

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
- backend/src/main/java/com/votogether/domain/post/dto/request/PostOptionUpdateRequest.java
- backend/src/main/java/com/votogether/domain/post/dto/request/PostUpdateRequest.java
- backend/src/main/java/com/votogether/domain/post/entity/Post.java
- backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
- backend/src/main/java/com/votogether/domain/post/service/PostService.java
- backend/src/main/java/com/votogether/domain/post/util/ImageUploader.java
- backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
- backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
close: #321 
게시글 수정 기능 구현
5시간 (코드 리팩토링에 예상보다 많은 시간을 들이게 되었습니다.)
1. 작성자인 경우에만 수정 가능
2. 마감기한이 아직인 경우에만 수정 가능
3. 마감 기한 수정은 생성일로부터 최대 3일 이후까지만 가능
> 게시글 수정 기능 구현

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
- backend/src/main/java/com/votogether/domain/post/entity/Post.java
- backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
- backend/src/main/java/com/votogether/domain/post/repository/PostContentImageRepository.java
- backend/src/main/java/com/votogether/domain/post/service/PostService.java
- backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
close: #322 
게시글 삭제기능 구현 및 투표 20개 이상인 경우 예외 처리 기능 구현
15분
-  게시글 삭제 기능
-  20명 이상 투표한 경우 삭제 불가
> 게시글 삭제기능 구현 및 투표 20개 이상인 경우 예외 처리 기능 구현

- backend/src/main/java/com/votogether/domain/post/dto/response/PostOptionResponse.java
- backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
- backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
- backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostOptionDetailResponse.java
- backend/src/main/java/com/votogether/domain/post/service/PostService.java
* close: #346
게시글 응답에는 이미지 경로 포함하도록 수정하였습니다.
5분
이미지 경로 응답 필드를 추가하였습니다.
화이팅입니다 🔥
> 게시글 전체 조회 시 이미지 경로 포함하도록 수정

- backend/build.gradle
* close: #379
MySQL 의존성을 추가하였습니다.
5분
MySQL 의존성을 추가하였습니다.
질문, 반박 대환영입니다 :)
> MySQL 의존성 추가

- backend/build.gradle
- backend/src/main/resources/application.yml
- backend/src/main/resources/log4j2-dev.xml
- backend/src/main/resources/log4j2-local.xml
- backend/src/main/resources/log4j2-prod.xml
* close: #338
로그 설정 파일을 추가하였습니다.
1시간
팀원들이 다들 함께 진행한 작업이라 일정 추정에 맞게 진행할 수 있었습니다 :)
프로파일별로 로그 설정을 다르게 가져가는 전략을 선택하였습니다.
최강 보투게더 🔥
> 로그 설정 파일 추가

- frontend/src/api/postList.ts
- frontend/src/components/common/Dashboard/UserProfile/index.tsx
- frontend/src/components/common/Dashboard/UserProfile/style.ts
- frontend/src/components/common/Dashboard/profileStyle.ts
- frontend/src/components/common/Drawer/Drawer.stories.tsx
- frontend/src/components/common/NarrowMainHeader/NarrowMainHeader.stories.tsx
- frontend/src/components/common/NarrowMainHeader/index.tsx
- frontend/src/components/common/NarrowMainHeader/style.ts
- frontend/src/components/post/PostListPage/index.tsx
- frontend/src/pages/MyInfo/style.ts
close: #387
:[BUG] 모바일일때 검색 input 없음/ 로고버튼 이벤트 없음/ 개인정보 이동 불가
close: #367
:[BUG] 카테고리별 게시글이 보이지 않습니다
모바일일 때 검색 input 나오지 않음
모바일일 때 로고 버튼인데 이벤트 연결되어있지 않음
개인정보 페이지로 이동하는 트리거 없음
1시간
- 모바일일 때 검색 input 나오지 않음
- 검색 아이콘을 누르면 검색바가 나옴
- 검색바가 나와있는 상태에서 본문을 누르면 검색바가 감추어짐
- 모바일일 때 로고 버튼인데 이벤트 연결되어있지 않음
- nav "/"으로 이동 
- 개인정보 페이지로 이동하는 트리거 없음
- userInfo에서 사용자이름에 링크를 연결
- 마이페이지에서 사용하는 userInfo는 path를 확인해서 링크를 연결하지 않음
- 카테고리 불러와지지 않는 오류 해결
- url 오타수정 
> [BUG] 모바일일때 검색 input 없음/ 로고버튼 이벤트 없음/ 마이페이지 이동 불가

- frontend/src/components/common/Post/index.tsx
- frontend/src/pages/post/PostDetail/BottomButtonPart/BottomButtonPart.stories.tsx
- frontend/src/pages/post/PostDetail/BottomButtonPart/index.tsx
- frontend/src/pages/post/PostDetail/PostDetail/index.tsx
close: #393 
- 비회원인데 신고가 가능한 버그, 비회원이 투표한 경우 토스트 띄우기
20분
처음에 너무 넉넉잡아 책정했던 것 같습니다
비회원이 투표했을 시 문구
비회원이 신고했을 시 문구
문구가 적당한가요?
> 비회원인데 신고가 가능한 버그, 비회원이 투표한 경우 토스트 띄우기

- frontend/__test__/hooks/query/useCancelMembership.test.tsx
- frontend/src/components/comment/CommentList/CommentLoginSection/index.tsx
- frontend/src/components/common/Dashboard/index.tsx
- frontend/src/hooks/context/auth.tsx
- frontend/src/hooks/query/user/useWithdrawalMembership.ts
- frontend/src/pages/MyInfo/DeleteMemberModal/index.tsx
- frontend/src/pages/MyInfo/DeleteMemberModal/style.ts
- frontend/src/pages/MyInfo/index.tsx
- frontend/src/pages/MyInfo/style.ts
close: #394 
* 로그인했는데 마이페이지로 리다이렉트되는 버그 해결
* 마이페이지에서 회원탈퇴 모달(DeleteMemberModal) 분리 
* 회원탈퇴에 실패하는 버그 (API 연결 중..)
* useWithdrawalMembership query에서 query key에 로그인 여부(isLoggedIn) 추가
* 50분 (백엔드 API 수정 완료 후, 기능 제대로 구현되는지 확인 후 머지하겠습니다!)
* 회원탈퇴 모달 분리한 이유? => react query에서 주는 error, isError, isSuccess를 받아서 활용하려면 자식 컴포넌트를 만들어야 했습니다.. CreatePostPage 처럼요!) 
> 로그인했는데 마이페이지로 리다이렉트되는 버그, 회원탈퇴에 실패하는 버그 해결

- backend/src/main/java/com/votogether/domain/post/entity/Post.java
- backend/src/main/java/com/votogether/domain/post/entity/PostOptions.java
close: #444 
PostOption이 수정할 때 전부 지워지도록 개선
10분
PostOption이 수정할 때 전부 지워지도록 개선
> PostOption이 수정할 때 전부 지워지도록 개선

- frontend/src/hooks/query/post/useEditPost.ts
close: #463
- queryClient.invalidateQueries 키 수정
5분
- queryClient.invalidateQueries 키 수정
> [BUG] 상세 게시글에서 이미지 수정 후 새로고침해야 바뀐 이미지로 보여요

- frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
- frontend/src/pages/MyInfo/index.tsx
close: #464 
- useEffetct의 인자로 들어있던 openToast 삭제
10분
> 토스트가 계속해서 뜨는 문제 수정

- frontend/src/components/common/Accordion/Accordion.stories.tsx
- frontend/src/components/common/Accordion/index.tsx
- frontend/src/components/common/AddButton/AddButton.stories.tsx
- frontend/src/components/common/DeleteModal/index.tsx
- frontend/src/components/common/Modal/index.tsx
- frontend/src/components/common/Modal/style.ts
- frontend/src/components/common/TwoButtonModal/index.tsx
close: #410 
- 아코디언 aria-label이 열기, 닫기와 같이 상태에 따라 다르게 들리도록 설정
- 아코디언을 열고 닫는 탭에 포커스가 가도록 탭 인덱스 추가
- 더하기 버튼(사용하는 측에서 aria-label을 사용하면 되는 것이여서 따로 작업하지 않았음)
- 모달 ( 안보이는 버튼을 만들어 포커스 되었을 때 팝업창 닫기라고 들리고, 눌렀을 때 닫히도록 구현)
- 삭제 모달 (게시글 삭제하기를 제목: 게시글 삭제하기 와 같이 '제목:'을 붙혔고, 텍스트에 포커스가 되도록 탭 인덱스를 설정)
30분
> Accordion, AddButton, Modal, TwoButtonModal, DeleteModal 웹접근성 높이기

- frontend/src/api/ranking.ts
- frontend/src/constants/queryKey.ts
- frontend/src/hooks/query/ranking/usePassionUserRanking.ts
- frontend/src/hooks/query/ranking/usePopularPostRanking.ts
- frontend/src/hooks/query/ranking/useUserRanking.ts
- frontend/src/types/ranking.ts
close: #504
리액트 쿼리를 사용하여 작성
- 내 랭킹정보 가지고 오기
- 열정유저 가지고 오기
- 인기글유저 가지고 오기
1시간
(크게 뭐 할게 없더라구요.. 쉬엄쉬엄 했습니다)
아직 api가 정해지지 않아 타입이 어떻게 될 지 모르겠어서 type은 제외하고 작성했습니다.
머지가 되기 전 api가 정해지면 타입 지정하고 가고자 합니다.
- 내 랭킹정보 가지고 오기: QUERY_KEY.USER_INFO, isLoggedIn + passionUser
- 열정유저 가지고 오기: passionUser
- 인기글유저 가지고 오기: popularPost
> 랭킹 시스템 패치 함수 및 훅 만들기

- frontend/src/components/VoteStatistics/OneLineGraph/index.tsx
- frontend/src/components/VoteStatistics/TwoLineGraph/index.tsx
- frontend/src/components/VoteStatistics/index.tsx
- frontend/src/components/common/Dashboard/GuestProfile/index.tsx
- frontend/src/components/common/Dashboard/UserProfile/index.tsx
- frontend/src/components/common/Dashboard/profileStyle.ts
- frontend/src/components/common/Toast/index.tsx
- frontend/src/components/common/UpButton/index.tsx
- frontend/src/pages/VoteStatisticsPage/OptionStatistics/index.tsx
- frontend/src/pages/VoteStatisticsPage/OptionStatistics/style.ts
close: #408 
* 대시보드 컴포넌트, 통계 컴포넌트, UpButton 웹접근성을 개선하였습니다.
* 1시간 반 (Toast 컴포넌트는 우스가 이미 필요한 속성을 추가해주셨습니다👍👍)
* aria-label 속성 등을 추가하여 웹접근성을 개선했습니다.
* 모바일 안드로이드 기준(구글 Talkback)으로 웹접근성을 테스트하였습니다.
> 대시보드 컴포넌트, 통계 컴포넌트, UpButton 웹접근성 높이기

- .github/workflows/frontend-lighthouse-ci.yml
- frontend/.lighthouserc.js
- frontend/package-lock.json
- frontend/src/components/post/EmptyPostList/index.tsx
- frontend/src/components/post/EmptyPostList/style.ts
- frontend/src/components/post/PostList/index.tsx
- frontend/src/components/post/PostListPage/index.tsx
- frontend/src/components/post/PostListPage/style.ts
close: #542 
close: #548 
close: #457
* lighthouse 측정 결과를 알려주는 github workflow를 구현함 (#542)
* 모바일에서 위로가기, 게시글 작성이 잘려서 보이는 버그 해결함 (#548)
* EmptyPostList, PostList, PostListPage 웹 접근성 개선함. (#457)
약 6시간 (10분+4시간+1.5시간)
lighthouse 관련 코드 설명은 코멘트로 남기겠습니다.
~~lighthouse github action은 이 pr이 머지된 이후, 앞으로 올리는 pr들에 대해 아래와 같이 코멘트로 검사 결과를 알려주는 것을 확인할 수 있습니다!~~ -> 이제 확인 가능!!
* 위로가기&게시글 작성 버튼 을 스크린 리더가 어떻게 읽게 해야 할지 감이 잡히지 않네요.. 현재 스크린리더가 읽는 흐름은, `진행중 -> 최신순 -> 첫번째 게시글 -> 두번째 게시글 -> 세번째...` 이런 식입니다. 이렇게 되면 게시글 작성 버튼을 읽을 수가 없는데 어떻게 해야  될까요..? (참고로 이런 레이아웃과 비슷한 예시가 네이버 메일(모바일)의 메일작성버튼 이 있는데, talkback으로 읽어봤는데 작성버튼을 아예 읽지를 않더라구요..)
> lighthouse 결과를 알려주는 github action 구현, 웹접근성 개선, 반응형 관련 버그 1건 수정

- backend/src/main/java/com/votogether/domain/post/dto/response/post/PostRankingResponse.java
close: #576 
바인딩 되는 응답객체의 필드 변수명을 수정하였습니다,
기능 구현에 소요된 시간을 적어주세요. (추정했던 시간과 다르다면 이유도 함께)
> response 필드 변수 수정

- backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
- backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
close: #599 
CORS Credential설정 및 cookie samesite설정했습니다.
30분
> CORS Credential설정 및 cookie samesite설정

- backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
close: #627 
개발서버 cors 오리진 url 수정
1분 
> [fix] 개발서버 오리진 url 수정

- backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
close: #629 
로컬 호스트 https url 오리진 추가
1분
> https 로컬호스트 오리진 url 추가

- frontend/src/api/token.ts
close: #649 
- 리프레시 토큰 명세와 다른 코드 수정
- 
20분(알아내는 시간이 있었음)
명세와 다르게 일반 string값으로 바로 줬더라구요 그 부분을 고쳤습ㅂ니다
> 리프레시 토큰 명세와 다른 코드 수정

- frontend/src/api/userInfo.ts
close: #661 
- 로그아웃 시 쿠키를 보내도록 설정
5분
> fix: (#661) 로그아웃 시 쿠키를 보내도록 설정

- frontend/src/components/comment/CommentList/style.ts
close: #673 
- 댓글 더 보기시 보이지 않는 인풋에 포커스되어 네모 박스가 보이는 문제 수정
5분
보이지 않는 인풋에 outline :none 을 해주었습니다
> 댓글 더 보기시 보이지 않는 인풋에 포커스되어 네모 박스가 보이는 문제 수정

- backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
close: #
프론트엔드 미션을 위한 CORS url 을 추가하였씁니다.
기능 구현에 소요된 시간을 적어주세요. (추정했던 시간과 다르다면 이유도 함께)
> [TEMP] CORS url 추가

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
close: #760 
- 디자인 시스템 설치 및 프로바이더 설정
5분
> 디자인 시스템 설치 및 프로바이더 설정

- frontend/src/components/post/Post/index.tsx
- frontend/src/components/post/Post/style.ts
- frontend/src/components/post/PostList/style.ts
close: #745 
- 작성시간 | 마감시간이 좁아져서 보이던 문제 해결
20분 (생각보다 어느 지점에서 문제가 되는 지 찾기 어려웠음)
> 작성시간 | 마감시간이 좁아져서 보이던 문제 해결

- backend/src/main/java/com/votogether/domain/alarm/repository/AlarmRepository.java
- backend/src/main/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepository.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
close: #788 
data-jpa 메서드 명에 top을 추가했습니다.
10분
없음.
없음.
> 가장 최신 값을 가져오도록 data jpa 메서드명 변경

- backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
close: #806 
필터에서 notices url 수정
1분
> 필터에서 notices url 수정

- backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
> refactor: https uri 삭제
