woowacourse-teams/2023-votogether

- backend/src/main/java/com/votogether/domain/member/entity/Gender.java
- backend/src/main/java/com/votogether/domain/member/entity/Member.java
- backend/src/main/java/com/votogether/domain/member/entity/MemberCategory.java
- backend/src/main/java/com/votogether/domain/member/entity/SocialType.java
- backend/src/main/java/com/votogether/domain/member/repository/MemberRepository.java
- backend/src/main/java/com/votogether/domain/vote/entity/Vote.java
close: #7 
Member, MemberCategory, Vote 엔티티 구현했습니다.
- 각각 엔티티 구현하고 연관관계 매핑은 전부 진행하지 않았습니다.
- Vote와 MemberCategory는 필요에 따라 Repository를 만드는 것으로 결정하여
Repository를 생성하지 않았습니다.
없음
> 멤버의 Entity, Repository 구현

- backend/build.gradle
- backend/src/main/java/com/votogether/VotogetherApplication.java
- backend/src/main/java/com/votogether/config/JpaConfig.java
- backend/src/main/java/com/votogether/config/OpenAPIConfig.java
- backend/src/main/java/com/votogether/domain/common/BaseEntity.java
- backend/src/main/java/com/votogether/domain/healthcheck/controller/HealthCheckController.java
- backend/src/main/java/com/votogether/domain/healthcheck/service/HealthCheckService.java
- backend/src/main/java/com/votogether/domain/post/entity/Post.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/votogether/VotogetherApplicationTests.java
close: #26
JPA Auditing 설정과 Swagger 설정을 진행하였습니다.
- @EnableJpaAuditing을 통해 Auditing 동작이 수행되도록 하였습니다.
- Swagger 사용을 위한 openapi 의존성을 추가하고 OpenAPI 설정을 수행하였습니다.
- 서버의 정상 작동 여부를 확인하고 서버의 상태를 주기적으로 확인하는 헬스 체크 기능을 구현하여 Swagger 예시 코드를 작성해보았습니다.
백엔드 화이팅 🔥
> Jpa Auditing, Swagger 설정

- .github/workflows/backend-pr-test.yml
- .gitignore
close: #33
PR 진행 시 테스트를 진행하고, 테스트 성공 시 merge가 가능하도록 하는 기능을 구현하였습니다.
- `main`, `dev` 브랜치에 PR 진행 시 테스트를 선행으로 진행합니다.
- 테스트 결과가 PR 코멘트로 등록됩니다.
- 실패하는 테스트가 존재하는 경우
- merge 동작을 수행할 수 없습니다.
- files changed에 실패하는 코드 라인에 check가 등록됩니다. 해당 체크는 테스트가 통과하면 자동으로 사라집니다.
- Slack 채널을 통해 알림이 발생합니다.
- 오류를 수정 후 해당 PR에 다시 커밋하게 되면 workflow가 자동으로 다시 실행됩니다.
- 슬랙 앱을 통해 채널 웹훅을 설정합니다.
- 레포지토리의 시크릿 값을 입력합니다.
- 워크플로우가 통과되지 않으면 merge가 되지 않도록 브랜치 정책을 설정합니다.
현재 백엔드 프로젝트에 대해서만 설정한 workflow가 동작하도록 되어있습니다. workflow가 정상적으로 통과되지 않으면 merge가 되지 않도록 설정하고자 했는데 그럴 경우 프론트 PR에 대해서는 workflow가 동작하지 않아 merge를 할 수 없는 문제가 발생합니다. 이 부분을 어떻게 하면 좋을지 의논해보고 싶어요 :)
> PR 진행 시 테스트 통과 선행 기능 구현

- backend/src/main/java/com/votogether/domain/category/contorller/CategoryController.java
- backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
- backend/src/main/java/com/votogether/domain/member/repository/MemberCategoryRepository.java
- backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
- backend/src/test/java/com/votogether/domain/member/repository/MemberCategoryRepositoryTest.java
close: #66 
(회원) 선호 카테고리 추가 기능 구현
회원이 선호하는 카테고리를 선호 카테고리 목록에 추가하는 기능입니다.
컨트롤러와 서비스 단위 테스트는 추후에 리펙터링 할 예정입니다.
- 추정시간 : 1시간
- 개발시간 : 1시간정도
- 이야기하면서 개발하다보니 시간 좀 걸림
- 집중하면서 하면 30분내로, 컨트롤러와 서비스 단위테스트까지 작성한다면 50분 정도 걸릴거같음
> (회원) 선호 카테고리 추가 기능 구현

- frontend/src/components/common/Dashboard/style.ts
- frontend/src/components/common/Layout/Layout.stories.tsx
- frontend/src/components/common/Layout/index.tsx
- frontend/src/components/common/Layout/style.ts
close: #62 
1시간 30분
📦Layout
┣ 📜Layout.stories.tsx
┣ 📜index.tsx
┗ 📜style.ts
```tsx
interface LayoutProps extends PropsWithChildren {
userInfo?: User; // 유저 정보
categoryList: Category[]; // 카테고리 리스트
selectedCategory?: string; // 선택된 카테고리
isSidebarVisible: boolean; // 사이드바를 보일지 유무 
handleFavoriteClick: (categoryId: number) => void; // 즐겨찾기 클릭
handleLogoutClick: () => void; // 로그아웃 클릭
}
```
- 모바일 화면에서는 와이드 헤더와 사이드바가 보이지 않음
- 모바일 이상에서는 와이드 헤더와 사이드바가 보임
- 사이드바를 isSidebarVisible 이라는 props로 숨기거나 보이게 함
- 콘텐츠가 보이는 곳에 사이드바가 있다면 max-width :500px, 없다면 max-width를 설정하지 않음
- 사이드바엔 aside 태그, children이 들어갈 곳엔 main 태그를 두어 의미있는 태그를 사용하고자 함
Layout와 같은 컴포넌트를  common 폴더에서 관리했는지 혹은 layout 폴더를 따로 만들어 관리했는지 궁금합니다
저는 layout 폴더를 따로 만들었던 것 같아서요
> 레이아웃 컴포넌트 구현

- frontend/__test__/api/user.test.ts
- frontend/src/api/wus/userInfo.ts
- frontend/src/mocks/handlers.ts
- frontend/src/mocks/mockData/user.ts
- frontend/src/mocks/wus/userInfo.ts
- frontend/src/types/user.ts
close: #63 
1시간
- 유저 정보를 불러오는 패치 함수 (/members/me) 구현
- 이를 모킹할 수 있는 msw 코드 구현
아래와 같이 서버에서 받아온 데이터를 클라이언트에서 사용하는 api 명세로 바꾸었습니다. 하지만 서버에서 받아온 것이나 클라이언트에서 받아온 것이나 똑같이 보이는데요. 이렇게 한 이유는 아래와 같이 백앤드에서 보내줄 데이터의 이름이 변경이 많이 될 것이 예상되었기 때문입니다 👍
```tsx
import { ServerUser, User } from '@type/user';
import { getFetch } from '@utils/fetch';
export const transformUserInfoResponse = (userInfo: ServerUser): User => {
const { nickname, postCount, userPoint, voteCount, badge } = userInfo;
return {
nickname,
postCount,
userPoint,
voteCount,
badge,
};
};
export const getUserInfo = async () => {
const userInfo = await getFetch<ServerUser>('/members/me');
return transformUserInfoResponse(userInfo);
};
```
> 유저 정보를 불러오는 패치 api 함수 구현 및 msw mocking 구현

- backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
- backend/src/main/java/com/votogether/domain/auth/service/KakaoOAuthClient.java
close: #121 
엑세서 토큰 요청 시 헤더 타입을 명시해줬습니다.
회원 닉네임이 잘못나오는 버그를 수정했습니다.
없음.
없음.
> 카카오에 엑세스 토큰 요청 시 타입 설정 및 회원 닉네임 반환 오류 수정

- frontend/__test__/api/postList.test.ts
- frontend/__test__/hooks/query/usePostList.test.tsx
- frontend/src/api/wus/postList.ts
- frontend/src/components/post/PostList/constants.ts
- frontend/src/components/post/PostList/index.tsx
- frontend/src/constants/post.ts
- frontend/src/hooks/query/usePostList.tsx
- frontend/src/mocks/handlers.ts
- frontend/src/mocks/wus/post.ts
- frontend/src/routes/router.tsx
close: #110 
약 1시간
- 카테고리별 게시글 조회 기능 패치 함수 구현
- usePostList에서 전체 게시글 조회뿐만 아니라 카테고리별 게시글 조회 기능도 추가
- PostList 컴포넌트에서 주소에 categoryId가 있다면 카테고리별 게시글 조회를 하도록 구현
window.location.search로 `?categoryId=1` 과 같이 뒤에 붙은 url을 가져왔음
그리고 URLSearchParams를 통해 categoryId의 값을 구해 카테고리별 글 목록을 요청함
```tsx
const URL = new URLSearchParams(window.location.search);
const categoryId = URL.get(CATEGORY_ID);
```
> 카테고리별 게시글 조회 기능을 위해 getPostList 함수 수정 이후 usePostList 훅 추가 기능 구현

- backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
close: #138
Swagger 사용을 위해 Swagger URI로 시작하는 경로는 허용하도록 수정하였습니다.
- `contains`로는 모든 하위 경로를 확인할 수 없습니다. 따라서 `startsWith`를 통해 하위 경로를 허용하도록 수정하였습니다.
> Swagger 페이지에 정상적으로 접근할 수 없는 오류

- frontend/src/components/PostForm/index.tsx
close: #145
- 게시글 수정 api 명세 변경에 따라 코드 변경
- 생각보다 큰 변화가 없습니다..
- 없습니다
> 게시글 수정 api 변경에 따른 적용_Feat/#145

- frontend/__test__/api/postList.test.ts
- frontend/__test__/getPathFragment.test.ts
- frontend/__test__/hooks/query/usePostList.test.tsx
- frontend/jest.setup.js
- frontend/package.json
- frontend/src/api/postList.ts
- frontend/src/components/post/PostList/index.tsx
- frontend/src/components/post/PostListPage/constants.ts
- frontend/src/components/post/PostListPage/types.ts
- frontend/src/constants/path.ts
- frontend/src/constants/post.ts
- frontend/src/hooks/query/post/usePostListKind.ts
- frontend/src/hooks/query/usePostList.tsx
- frontend/src/hooks/usePostRequestInfo.ts
- frontend/src/mocks/handlers.ts
- frontend/src/mocks/mockData/postList.ts
- frontend/src/mocks/wus/post.ts
- frontend/src/types/post.ts
- frontend/src/utils/getPathFragment.ts
close: #127 
- 내가 작성한 게시글 조회 fetch 조회 함수
- 내가 투표한 게시글 조회 fetch 조회 함수
- msw 코드 작성
- 기존의 게시글 목록을 불러오는 훅 변경
- 현재 어느 페이지인지 확인하는 훅 및 유틸 함수 구현
- 홈페이지, 내가 작성한 글 페이지, 내가 투표한 글 페이지, 카테고리별 글 페이지에서 알맞은 API를 불러오도록 연동
- 홈페이지, 내가 작성한 글 페이지, 내가 투표한 글 페이지, 카테고리별 글 페이지 모두 하나의 컴포넌트 HomePage를 사용하였음 => 이유는 게시글 목록을 불러오는 기능이 모두 같기 때문
- 현재 어느 페이지인지 확인하는 유틸 함수를 만든 이유는 useLocation의 pathname을 이용하려고 했으나 category/1 과 같이 따로 가공해야하는 경우가 있어서 만들게 되었음
- posts/me를 사용하는 환경에서 테스트가 실패했는데 그 이유는 MSW handlers의 순서가 원인이였습니다.
아래와 같이 /posts/me가 /posts/:postId 보다 위에 있어야 하는데요. 그 이유는 다음과 같습니다. 
```bash
/posts/me 가 /posts/:postId 보다 위에 있어야 하는 이유는 라우팅 순서 때문입니다.
Express나 Node.js에서는 라우팅 경로와 일치하는 첫 번째 핸들러 함수를 실행합니다. 
만약 /posts/me 가 /posts/:postId 보다 아래에 있다면, /posts/me 경로도 /posts/:postId 경로와 일치하게 됩니다. 
이렇게 되면 /posts/me 요청도 /posts/:postId 핸들러 …
```
> 내가 작성한 게시글 조회, 내가 투표한 게시글 조회 기능 구현

- backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
- backend/src/main/java/com/votogether/domain/member/controller/MemberController.java
- backend/src/main/java/com/votogether/domain/member/dto/MemberNicknameRequest.java
- backend/src/main/java/com/votogether/domain/member/dto/MemberNicknameUpdateRequest.java
- backend/src/main/java/com/votogether/domain/member/entity/Member.java
- backend/src/main/java/com/votogether/domain/member/entity/Nickname.java
- backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
- backend/src/main/java/com/votogether/domain/member/repository/MemberRepository.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
- backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
- backend/src/test/java/com/votogether/domain/member/repository/MemberRepositoryTest.java
- backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
close: #139 
닉네임 수정 기능 추가
- 중복된 닉네임 불가
- 닉네임 길이 2~15자
- 한글, 영어, 숫자를 제외한 문자는 불가능하도록
없음.
> 닉네임 수정 기능 구현

- backend/src/main/java/com/votogether/domain/member/controller/MemberController.java
- backend/src/main/java/com/votogether/domain/member/entity/Member.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
- backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
- backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
close: #141 
회원 탈퇴 기능 구현
회원 탈퇴 기능 구현
회원 닉네임 생성 시 공백이  들어가는 것 제거
없음.
> 회원 탈퇴 기능 구현

- frontend/src/components/common/MultiSelect/MultiSelect.stories.tsx
- frontend/src/components/common/MultiSelect/index.tsx
- frontend/src/components/common/MultiSelect/style.ts
- frontend/src/components/common/MultiSelect/types.ts
- frontend/src/hooks/useMultiSelect.ts
close: #44 
```TypeScript
interface MultiSelectProps {
selectedOptionList: Option[];  // 선택된 옵션 리스트 
optionList: Option[];  // 모든 옵션 리스트 (ex. 카테고리 목록)
handleOptionAdd: (newItem: Option) => void; // selectedOptionList 에 클릭한 옵션 추가하는 함수
handleOptionDelete: (optionId: number) => void; // selectedOptionList 에서 클릭한 옵션 제거하는 함수
placeholder?: string; // 선택된 옵션이 아무것도 없는 경우 
}
```
* 스토리는 총 4개입니다.
* 기존에 선택한 옵션들이 없는 경우
* 기존에 선택한 옵션들이 있는 경우
* 기존에 선택한 카테고리 옵션이 없는 경우
* 기존에 선택한 카테고리 옵션이 있는 경우
* `useRef` 를 이용하여, 옵션 개수에 따라 DropDown(미선택된 옵션들을 감싸는 div)의 높이(clientHeight)를 조절합니다. -> 이 부분은 코멘트로 자세히 설명해보겠습니다!
* `useMultiSelect` 라는 커스텀 훅은, 기존에 선택한 옵션 리스트(initialOptionList)와 옵션 개수 제한값(optionCountLimit)을 매개변수로 받습니다.
* 매우 긴 텍스트의 옵션을 클릭하면, up down (위아래 svg 아이콘)이 가려지는데 어떻게 해결해야 할지 CSS 팁 알려주시면 감사하겠습니다🥺 (Wrapper 클릭하면, 열고 …
> 다중 선택 컴포넌트 구현

- backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
- backend/src/main/java/com/votogether/domain/post/dto/request/CommentUpdateRequest.java
- backend/src/main/java/com/votogether/domain/post/entity/comment/Comment.java
- backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
- backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
- backend/src/test/java/com/votogether/domain/post/entity/comment/CommentTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostCommentServiceTest.java
close: #130
댓글 수정 기능을 구현하였습니다.
- 게시글, 댓글이 유효한지 검증합니다.
- 해당 게시글의 댓글인지, 댓글 작성자가 맞는지 검증합니다.
- 수정하고자 하는 내용이 올바른지 검증합니다.
- 댓글을 수정합니다.
- 추후 리팩토링 시 Swagger 어노테이션을 따로 빼도록 해야할 것 같아요!
- 매개변수 순서도 코드 컨벤션으로 정하면 좋을 것 같아요 :)
> 댓글 수정 기능 구현

- frontend/src/components/common/Dashboard/CategoryToggle/CategoryToggle.stories.tsx
- frontend/src/components/common/Dashboard/CategoryToggle/index.tsx
- frontend/src/components/common/Dashboard/Dashboard.stories.tsx
- frontend/src/components/common/Dashboard/index.tsx
- frontend/src/components/common/Drawer/Drawer.stories.tsx
- frontend/src/components/common/Layout/index.tsx
- frontend/src/components/post/PostListPage/index.tsx
- frontend/src/constants/queryKey.ts
- frontend/src/hooks/query/category/useCategoryFavoriteToggle.ts
- frontend/src/hooks/query/category/useCategoryList.ts
- frontend/src/hooks/query/user/useUserInfo.ts
- frontend/src/mocks/wus/categoryList.ts
- frontend/src/utils/fetch.ts
close: #108 
close: #109 
* 카테고리 목록 조회, 카테고리 즐겨찾기, 유저 정보 조회에 대한 커스텀 쿼리들을 구현하여, fetch 함수들로 서버와 통신하고 서버 상태를 get, mutate 합니다.
* handleFavoriteClick 함수들을 여러 번 넘겨주는, props drilling 현상을 해결하였습니다. (onClick에 할당할 함수인 mutate를, CategoryToggle 컴포넌트에서 불러주고 있습니다. 이렇게 하면 handleFavoriteClick 함수를 아래로 계속 넘겨줄 필요가 없어집니다.) 
* 카테고리 목록을 조회하는 쿼리 구현(useCategoryList)
* 카테고리를 즐겨찾기 등록 및 해제하는 쿼리 구현(useCategoryFavoriteToggle)
* 유저 정보를 조회하는 쿼리 구현(useUserInfo)
* 현재 utils/fetch.ts 에서 deleteFetch 함수를 수정한 상태입니다.
*  상태코드 204인 경우 response가 json 형태이면 안된다고 함 -> response 만 return 하도록 수정함.
* 그런데 이렇게 하면 error 메시지를 잡을 수 없음 -> try-catch 구문을 이용해야 함.
* utils/fetch 내의 함수들을 try-catch 형식으로 바꾸려고 합니다! 이슈를 따로 파야할거 같아요~
---
* 따로 pr 날리는 거보다 쿼리 함수들 만드는 김에 issue 2개 동시에 완료했습니다~
> 카테고리 목록 조회, 카테고리 즐겨찾기, 유저 정보 조회에 대한 커스텀 쿼리 구현

- .github/workflows/frontend-storybook-deploy.yml
close: #165 
약 1시간
- dev로 보낸 PR이 머지될 때 스토리북이 배포되도록 함
- storybook-deploy 브런치에 스토리북 빌드된 파일을 올려서 깃허브 페이지로 배포되도록 함
배포된 사이트
https://woowacourse-teams.github.io/2023-votogether/
저희가 frontend, backend로 폴더가 나뉘어 있어서 이 부분 설정하는 것이 처음이라 까다로웠어요 !
> 스토리북을 PR이 merge 될 때 배포되도록 설정

- frontend/__test__/api/user.test.ts
- frontend/src/api/wus/userInfo.ts
- frontend/src/mocks/wus/userInfo.ts
- frontend/src/types/user.ts
- frontend/src/utils/fetch.ts
close: #153 
약 1시간
- 회원 닉네임 수정 fetch 함수 구현
- 회원 탈퇴 fetch 함수 구현
- MSW 코드 작성
아직 dev 브런치에 제로가 변경한 Fetch 유틸 함수 중 deleteFetch가 반영되어 있지 않아서 수동 반영하였습니다~
patchFetch 유틸 함수에서 body를 받는 옵션이 없어서 추가했습니다
react-query를 이용한 훅 구현은 따로 이슈 파도록 하겠습니다
> 회원 닉네임 수정, 회원 탈퇴 fetch 함수 구현 및 MSW 코드 작성

- backend/src/main/java/com/votogether/config/WebMvcConfig.java
- backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
- backend/src/main/java/com/votogether/domain/member/entity/Member.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
- backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
- backend/src/main/java/com/votogether/domain/post/dto/response/CommentResponse.java
- backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
- backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
- backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
- backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
- backend/src/test/java/com/votogether/domain/member/repository/MemberRepositoryTest.java
- backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
- backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
- backend/src/test/java/com/votogether/domain/post/repository/CommentRepositoryTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostCommentServiceTest.java
close: #129
게시글에 대한 댓글 목록 조회 기능을 구현하였습니다.
- 게시글에 대한 댓글 목록 조회 기능을 구현하였습니다.
- `@EntityGraph`를 사용하여 댓글 응답 시 항상 필요한 회원을 fetch join해서 가져오도록 하였습니다.
`LocalDateTime`이 응답으로 반환될 때 `@JsonFormat`을 사용하기에 `yyyy-MM-dd HH:mm`과 같은 형식으로 반환되는데 이걸 깔끔하게 테스트할 수 있는 방법이 떠오르지 않아요 ㅜ 도와주세요 고수분들
> 댓글 조회 기능 구현

- frontend/.storybook/main.ts
- frontend/__test__/api/postList.test.ts
- frontend/__test__/hooks/query/usePostList.test.tsx
- frontend/src/api/postList.ts
- frontend/src/components/PostForm/index.tsx
- frontend/src/components/common/SearchBar/index.tsx
- frontend/src/components/post/PostList/constants.ts
- frontend/src/components/post/PostList/index.tsx
- frontend/src/constants/post.ts
- frontend/src/hooks/query/usePostList.tsx
- frontend/src/hooks/usePostRequestInfo.ts
- frontend/src/mocks/wus/post.ts
- frontend/src/types/post.ts
close: #176 
- 헤더에 검색했을 때 검색한 키워드의 url로 이동하도록 함
- 검색 혹은 직접 url을 입력해서 들어왔을 때 해당 키워드에 대해 결과를 보여준다.
- 이에 대한 msw 코드, fetch 코드, react-query 코드가 추가 및 변경
useSearchParams를 이용해 keyword를 불러와 fetch하는 함수에 전달
content에 따라 다른 게시글을 불러오는 로직에서 content에 search를 추가
검색한 키워드를 100자 이내로 잘라서 요청
결과가 없다면 검색한 키워드에 대한 결과가 없다고 알려주는 컴포넌트가 필요한데 따로 이슈파서 디자인 후 진행하는 것이 좋아보입니다~
> 전체 게시글 목록 기능에 검색한 게시글 목록 기능 추가 구현 + 검색 기능 구현 + 스토리북 .env 설정

- frontend/src/components/common/Accordion/Accordion.stories.tsx
- frontend/src/components/common/Accordion/index.tsx
- frontend/src/components/common/Accordion/style.ts
- frontend/src/components/common/TimePickerOptionList/TimePickerOption/index.tsx
- frontend/src/components/common/TimePickerOptionList/TimePickerOption/style.ts
- frontend/src/mocks/example/get.ts
- frontend/src/pages/MyInfo/MyInfo.stories.tsx
- frontend/src/pages/MyInfo/index.tsx
- frontend/src/pages/MyInfo/style.ts
- frontend/src/routes/router.tsx
- frontend/src/styles/theme.ts
close: #175 
* Accordion 컴포넌트를 구현하였습니다. (common/Accordion)
* 내정보(닉네임, 포인트, 작성글, 투표수)를 조회할 수 있는 페이지 구현하였습니다.
* 해당 페이지에서 닉네임을 변경하거나 회원 탈퇴를 할 수 있도록 UI를 구현하였습니다. 
* Accordion props 
```TypeScript
interface AccordionProps extends PropsWithChildren {
title: string;  // 아코디언 제목
}
```
* MyInfo 페이지 Storybook
* 닉네임 변경, 회원 탈퇴, 유저 정보 조회 관련 API fetching 함수와 커스텀 쿼리 관련 코드들이 merge되어야 합니다. (임시로 mock data 사용함)
> 내 정보 페이지 UI 구현, Accordion 컴포넌트 구현

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
- backend/src/main/java/com/votogether/domain/post/dto/request/PostCreateRequest.java
- backend/src/main/java/com/votogether/domain/post/dto/request/PostOptionCreateRequest.java
- backend/src/main/resources/application.yml
multipartFile 관련 에러 디버깅
multipartFile 관련 에러 디버깅
> multipartFile 관련 에러 디버깅

- frontend/__test__/hooks/useMoreComment.test.tsx
close: #193 
- 테스트 실패로 인해 빌드가 안되는 문제 해결
- useMoreComment.test.ts 에서 MOCK_COMMENT_LIST => MOCK_TRANSFORMED_COMMENT_LIST로 변경
- 목 데이터를 서버의 댓글 리스트에서 클라이언트에서 사용하는 댓글 리스트로 변경
> 테스트 실패로 인해 빌드가 안되는 문제 수정

- frontend/env.d.ts
- frontend/src/pages/auth/Login.tsx
close: #204 
- VOTOGETHER_CLIENT_REDIRECT_URL => VOTOGETHER_SERVER_REDIRECT_URL 로 변경
> 카카오 리다이렉트 URL 환경 변수 변경

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
- backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
이미지 파일 관련 에러 추적을 위한 코드 추가
이미지 파일 관련 에러 추적을 위한 코드 추가
> 이미지 파일 관련 에러 추적을 위한 코드 추가

- frontend/src/components/PostForm/ContentImageSection/index.tsx
- frontend/src/components/PostForm/ContentImageSection/style.ts
- frontend/src/components/PostForm/index.tsx
close: #210
- 글작성 폼 이미지 파일 잘못 전달되는 오류 수정 
- mock 카테고리 id가 전달되는 오류  수정
- 글작성 폼 이미지 파일 잘못 전달되는 오류 수정  > 본문에 사진이 들어가면 input이 사라져 사진 파일이 날아가는 문제 수정
- mock 카테고리 id가 전달되는 오류  수정 > ```selectedOptionList.map(option => option.id)``` 코드 추가
> 글작성 폼 이미지 파일 잘못 전달되는 오류 수정 및 mock 카테고리 id가 전달되는 오류  수정_Feat/#210

- frontend/src/components/common/Post/index.tsx
- frontend/src/pages/MyInfo/index.tsx
close: #223
게시글 타입 수정에 따른 반영이 되지 않아 게시글 컴포넌트에서 발생하는 오류 수정
다른 pr에서 게시글 타입 중 startTime, endTime을 creatTime, deadline으로 수정
이 부분이 반영이 되지 않아 오류 발생
> 게시글 타입 수정에 따른 반영이 되지 않아 게시글 컴포넌트에서 발생하는 오류 수정

- frontend/__test__/hooks/query/useCreateVote.test.tsx
- frontend/__test__/hooks/query/useEditVote.test.tsx
- frontend/src/api/post.ts
- frontend/src/components/common/Post/index.tsx
- frontend/src/constants/post.ts
- frontend/src/constants/queryKey.ts
- frontend/src/hooks/query/post/useCreatePost.ts
- frontend/src/hooks/query/post/useCreateVote.ts
- frontend/src/hooks/query/post/useEditVote.ts
- frontend/src/hooks/query/usePostList.tsx
- frontend/src/hooks/usePostRequestInfo.ts
- frontend/src/mocks/vote.ts
- frontend/src/utils/fetch.ts
close: #220 
- 게시글 생성 후 게시글 목록 페이지로 이동하는데 새로 고침을 해야 게시글이 보이는 버그 수정
- 투표지 선택 후 새로 고침을 해야 투표지 선택이 반영되는 버그 수정
- 포스트 생성 후 리엑트 쿼리를 통한 캐시 메모리를 초기화한다.
- 투표지 선택 후 리엑트 쿼리를 통해 캐시 메모리를 초기화한다.
투표지 선택 후 낙관적 업데이트는 어려운 작업인 것 같아 다음 기회로 미뤄보려고 합니다
> 게시글 생성, 투표지 선택 시 새로 고침해야 적용되는 버그

- frontend/src/api/comment.ts
- frontend/src/components/comment/CommentList/CommentItem/index.tsx
- frontend/src/components/comment/CommentList/CommentTextForm/CommentTextForm.stories.tsx
- frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
- frontend/src/components/comment/CommentList/index.tsx
- frontend/src/constants/queryKey.ts
- frontend/src/hooks/query/comment/useEditComment.ts
- frontend/src/hooks/query/post/usePostDetail.ts
- frontend/src/mocks/comment.ts
- frontend/src/pages/post/PostDetail/index.tsx
- frontend/src/utils/cookie/index.ts
- frontend/src/utils/fetch.ts
close: #168 
* 글 상세 페이지에 댓글 관련 컴포넌트(CommentList, CommentDeleteModal 등 components/comment 하위 파일들 참고) 추가
* 댓글 관련 컴포넌트에 hooks/query/comment 의 커스텀 쿼리 연결하여 API 연동 완료
* usePostDetail 커스텀 쿼리 구현 -> 게시글 상세조회를 위한 쿼리
* 댓글 CRUD API 잘되는지 개발 서버 주소 들어가서 확인해봐야 합니다!
* 프론트 화이팅~
> 글 상세 페이지에 댓글 관련 컴포넌트 추가 및 댓글 CRUD API 연동 

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
- backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
- backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
- backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
close: #284 
비회원용 게시글 상세 조회 기능 구현했습니다.
filter에 `/guest`라는 suffix가 붙는 경우 필터를 거치지 않도록 수정했습니다.
GET메서드만 비회원일 때 필터를 통과하는 것도 추가했습니다!
이전 메서드 재활용 했습니다.
> (비회원) 게시글 상세 조회

- frontend/src/api/example.ts
- frontend/src/components/PostForm/index.tsx
- frontend/src/components/post/PostListPage/index.tsx
- frontend/src/hooks/query/post/useCreatePost.ts
- frontend/src/pages/ErrorBoundary.tsx
- frontend/src/pages/post/CreatePost/index.tsx
- frontend/src/utils/fetch.ts
close: #158 
* utils의 fetch 함수 리팩터링
* ErrorBoundary 구현
* query를 이용한 에러핸들링
* 페어프로그래밍을 통해 기존의 fetch 함수를 try-catch 구문으로 리팩터링하였습니다.
* API 응답으로 오는 에러 객체의 메시지를 화면(필요한 컴포넌트)에 보여줄 수 있게 되었습니다.
* ErrorBoundary를 class 로 구현하였습니다.
* 게시글 조회 및 생성 query를 이용하여 에러 핸들링을 하였습니다.
> utils의 fetch 함수 리팩터링, ErrorBoundary 구현, query를 이용한 에러핸들링

- frontend/src/hooks/query/category/useCategoryList.ts
- frontend/src/hooks/query/user/useUserInfo.ts
close: #308 
10분
- 유저 정보, 카테고리 목록에서 캐싱, 스테일 타임을 1시간으로 수정
현재 게시글 삭제가 dev에 머지되지 않았기에 때문에 추후 게시글 삭제시에 유저 정보 캐시를 초기화 해줘야 게시글 숫자가 적용될 것 같습니다
> 유저 정보, 카테고리 목록에서 캐싱, 스테일 타임을 1시간으로 수정

- frontend/__test__/getPathFragment.test.ts
- frontend/__test__/getSelectedState.test.ts
- frontend/src/components/common/Dashboard/Dashboard.stories.tsx
- frontend/src/components/common/Dashboard/index.tsx
- frontend/src/components/common/Drawer/Drawer.stories.tsx
- frontend/src/components/common/Layout/index.tsx
- frontend/src/components/post/PostListPage/index.tsx
- frontend/src/utils/post/getSelectedState.ts
close: #310 
- 유저가 어떤 게시글을 보고 있는지 정보를 반환하는 함수를 구현
- selectedCategory라는 props 변수명을 selectedState로 변경
- 대쉬보드, 모바일용 대쉬보드에 적용
usePostRequestInfo 훅에서 반환하는 정보를 이용하여 함수를 구현
```tsx
const { postOptionalOption, postType } = usePostRequestInfo();
```
전체 - 전체
검색 - 검색한 키워드
카테고리 - 선택한 카테고리 이름
내가 작성한 글 - 내가 작성한 글
내가 투표한 글 - 내가 투표한 글
위와 같이 보이도록 구현했습니다
예시 동영상
https://github.com/woowacourse-teams/2023-votogether/assets/80146176/8f2bb4d8-5be5-460d-a817-9a33d61865fc
> 현재 유저가 어떤 게시글 종류를 보고 있는지 정보를 반환하는 함수 구현 및 적용

- backend/src/main/java/com/votogether/domain/auth/dto/LoginResponse.java
- backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
- backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
* close: #331
카카오 회원가입/로그인 응답 형식을 수정하였습니다.
기존에 로그인 응답으로 전달하던 사용하지 않는 닉네임 필드를 제거하였습니다.
남은 레벨3 퐈이팅 🔥
> 카카오 회원가입/로그인 응답 형식 수정

- backend/src/main/java/com/votogether/domain/member/dto/MemberInfoResponse.java
- backend/src/main/java/com/votogether/domain/member/entity/Gender.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
- backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
* close: #332
내 정보 조회 응답 형식을 수정하였습니다.
기존의 응답 형식에서 추가적으로 성별과 출생년도 정보를 응답할 수 있도록 하였습니다.
성별 정보를 클라이언트에게 전달할 때 Enum명인 `MALE`, `FEMALE`로 전달할지, `남성`, `여성`으로 전달할지 고민이 됩니다 🤔
`MALE`, `FEMALE` 형식으로 전달하면 클라이언트에세 사용하기 위해 클라이언트에서 한번 더 가공할 것 같은데 서버에서 클라이언트에서 바로 사용할 수 있도록 정보를 가공해서 전달해주는 것이 더 좋다고 생각하였는데 다들 분들은 어떻게 생각하시는지 궁금합니다 :)
> 내 정보 조회 응답 형식 수정

- backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
- backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
- backend/src/main/java/com/votogether/domain/post/entity/Post.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
close: #317 
전체 게시글 조회시, 마감된 글은 투표 결과 전부 공개 기능 구현
전체 게시글 조회시, 마감된 글은 투표 결과 전부 공개 기능 구현
> 전체 게시글 조회시, 마감된 글은 투표 결과 전부 공개 기능 구현

- frontend/__test__/api/user.test.ts
- frontend/src/api/post.ts
- frontend/src/api/userInfo.ts
- frontend/src/components/PostForm/ContentImageSection/style.ts
- frontend/src/components/VoteStatistics/GraphStyle.ts
- frontend/src/components/VoteStatistics/TwoLineGraph/index.tsx
- frontend/src/components/VoteStatistics/TwoLineGraph/style.ts
- frontend/src/components/VoteStatistics/index.tsx
- frontend/src/components/VoteStatistics/style.ts
- frontend/src/components/VoteStatistics/type.ts
- frontend/src/components/common/Dashboard/Dashboard.stories.tsx
- frontend/src/components/common/Dashboard/UserProfile/UserProfile.stories.tsx
- frontend/src/components/common/Dashboard/UserProfile/index.tsx
- frontend/src/components/common/Drawer/Drawer.stories.tsx
- frontend/src/components/common/Post/index.tsx
- frontend/src/components/common/Post/style.ts
- frontend/src/components/common/TagButton/style.ts
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
- frontend/src/mocks/mockData/user.ts
- frontend/src/pages/post/PostDetail/index.tsx
- frontend/src/pages/post/PostDetail/style.ts
- frontend/src/types/user.ts
close: #334
- 게시물 상세페이지 반응성 적용 오류
- 변화한 사용자 정보 api 적용
- 게시물에 사진이 포함되어 있으면 활성화 표시 옆에 표시
- 통계 페이지 여자/남자 색상 안내 표시
- 게시물 상세페이지 반응성 적용 오류
- 상세페이지 게시글 본문이 작아지는 오류 수정 : width 적용
- 상세페이지 모바일버전에서 댓글이 본문과 가로길이가 다른 점 수정: 댓글에 margin 동일하게 적용
- 변화한 사용자 정보 api 적용
- 사용자 정보 api: 포인트/칭호 삭제 > 성별/나이 받기
- 게시글 목록 get api은 게시글 상세 response의 array형태라 수정할 부분 없음(서버에서는 원래 목록일때 imageUrl이 없었음)
- 게시물에 사진이 포함되어 있으면 활성화 표시 옆에 표시
- 목록/상세 모두 보임
- 통계 페이지 여자/남자 색상 안내 표시
- 성별보기로 갔을 때에만 보임 
아직 게시글 목록 get api가 서버에서 변경되지 않아 목록에서는 image가 다 있는 것으로 표시되나 상세페이지를 들어갔을 때 잘 적용되는 것을 확인함.
> [BUG] 게시물 상세페이지 반응성 적용 오류

- frontend/src/pages/post/EditPost/index.tsx
close: #355
:usePostDetail의 인수가 하나라서 발생하는 오류
usePostDetail의 인수가 하나라서 발생하는 오류 해결
5분..?
해당 부분에서 isGuest가 첫번째 인수로 들어가야 했는데 작성되지 않음.
글 수정페이지라 게스트가 진입할 수 없기 때문에(제로가 진입 못하도록 로직 구현 중이기 때문에) true로 설정해놓음.
> usePostDetail의 인수가 하나라서 발생하는 오류

- backend/src/main/java/com/votogether/domain/member/dto/MemberInfoResponse.java
- backend/src/main/java/com/votogether/domain/member/entity/Gender.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
- backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
* close: #341
성별, 출생년도 `null` 반환이 가능하도록 수정하였습니다.
3분
- 프론트 요청에 따라 성별 응답 형식을 `MALE`, `FEMALE`로 정하였습니다.
- 성별, 출생년도는 `null`이 들어갈 수 있기 때문에 `null` 반환이 가능하도록 하였습니다.
VoTogether팀 화이팅 🔥
> 성별, 출생년도 null 반환 가능하도록 수정

- backend/src/main/java/com/votogether/domain/member/controller/MemberController.java
- backend/src/main/java/com/votogether/domain/member/dto/MemberDetailRequest.java
- backend/src/main/java/com/votogether/domain/member/entity/Member.java
- backend/src/main/java/com/votogether/domain/member/entity/MemberCategory.java
- backend/src/main/java/com/votogether/domain/member/entity/Nickname.java
- backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
- backend/src/main/java/com/votogether/domain/post/entity/PostCategory.java
- backend/src/main/java/com/votogether/domain/post/entity/PostContentImage.java
- backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
- backend/src/main/java/com/votogether/domain/report/entity/Report.java
- backend/src/main/java/com/votogether/domain/vote/entity/Vote.java
- backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
- backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
- backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
close: #338 
테이블 unique 제약조건, 길이제한 등의 수정사항도 포함되어있습니다!
성별, 나이 수정기능 구현했습니다.
없음.
없음.
> 성별, 나이 수정 기능 구현

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
- backend/src/main/java/com/votogether/domain/post/service/PostService.java
- backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
close: #360 
전체 게시글 목록 조회 시 카테고리도 함께 조회할 수 있도록 변경했습니다.
1시간
쿼리 스트링에 카테고리 ID도 포함될 수 있도록 수정
하지만 category라는 쿼리스트링이 포함되지 않아도 조회 가능함
없음.
> 전체 게시글 목록 조회 시 카테고리도 함께 조회할 수 있도록 변경

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
- backend/src/main/java/com/votogether/domain/post/service/PostService.java
- backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
close: #313 
비회원으로 게시글을 검색하는 기능입니다.
10분 
회원으로 게시글 검색 하는 기능을 복붙하여 구현하였습니다.
컨트롤러와 서비스 계층에 비회원을 위한 게시글 검색 메서드가 추가되었습니다.
없음
> 비회원 게시글 검색 기능

- backend/src/main/java/com/votogether/domain/auth/dto/LoginResponse.java
- backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
- backend/src/main/java/com/votogether/domain/member/entity/Member.java
- backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
close: #374 
로그인 시 responseDto에 성별, 나이대가 Null인지 아닌지에 대한 필드 추가
10분
예상보다 테스트 의존이 많이 걸려있지 않아서 빠르게 수정했다.
없음.
없음.
> 로그인 시 응답하는 회원의 필수정보 필드 추가

- backend/src/main/java/com/votogether/config/OpenAPIConfig.java
- backend/src/main/resources/application.yml
- backend/src/test/resources/application.yml
* close: #347
환경 변수를 통해 로컬에서는 h2로 개발, 운영 환경에서는 MySQL로 동작하도록 하였습니다.
2시간
- CICD 파일 경로 및 정리하느라 소요된 시간이 존재합니다.
민감한 값들이나 변경되어야 하는 값들은 환경변수로 관리하도록 하였습니다.
질문 대환영입니다 :)
> MySQL 데이터소스 설정 추가

- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.common.js
close: #366 
- 웹팩 패키지 중 CopyPlugin으로 빌드 시 필요한 파일, 이미지를 복사하도록 설정
- 빌드에서 dist에 icons 폴더에 favicon, 아이콘 이미지, manifest 등의 파일이 생기도록 설정
30분
dist/icons 폴더  이미지
https://github.com/woowacourse-teams/2023-yozm-cafe/blob/main/client/webpack.config.js
https://webpack.kr/plugins/copy-webpack-plugin/#root
> 빌드 시 public/icons에 있는 favicon, 아이콘 등을 빌드하도록 설정

- frontend/__test__/calculateDeadlineTime.test.ts
- frontend/__test__/getSelectedTimeOption.test.ts
- frontend/src/components/PostForm/index.tsx
- frontend/src/utils/post/calculateDeadlineTime.ts
- frontend/src/utils/post/getSelectedTimeOption.ts
close: #370 
- 수정할 때 글에서 설정한 마감시간이 초기값이 설정되도록 구현
1시간 30분
살려주세요
- 선택된 시간 문자를 반환하는 함수에서 null을 반환하도록 함 , undefined를 반환하는 것이 자연스럽지 않게 느껴졌어요
- 그래서 PostForm에서 null을 사용하도록 함
```tsx
const [selectTimeOption, setSelectTimeOption] = useState<DeadlineOption | '사용자지정' | null>(
getSelectedTimeOption(calculateDeadlineTime(createTime, deadline))
);
```
수정시 사진
게시글 생성시 사진 ( 마감시간을 선택해달라고 잘 되는 모습)
게시글 수정이 안되는 것은 왜 안되는지 잘 모르겠습니다  백앤드 로그에서 왜 실패 했는지를 확인해봐야 할 것 같아요 
그래서 마감시간만 수정해서 PR 올려요
> 게시글 수정을 할 때 마감시간이 설정되도록 구현

- frontend/src/hooks/query/post/useCreateVote.ts
- frontend/src/hooks/query/post/useEarlyClosePost.ts
- frontend/src/hooks/query/post/useEditVote.ts
- frontend/src/hooks/query/post/usePostDetail.ts
- frontend/src/pages/post/PostDetail/PostDetail/index.tsx
close: #369 
- usePostDetail에서 로그인 정보를 키 값으로 추가하여 새로고침시에도 올바르게 나오도록 수정 및 적용
30분
상세 게시글에서 새로고침 시
1. 상세 게시글 게스트용 패치
2. 로그인
이 때 다시 회원용 상세 게시글을 패치해와야 하는데 5분간 캐싱이 되어 있기 때문에 로그인하여도 값을 새로고침하지 않았음
상세 게시글 쿼리 키값에 로그인 여부를 추가하여 로그인했을 때 새롭게 패치해오도록 수정
투표 생성, 수정, 조기마감은 로그인한 경우에만 가능하니 기존에 상세 게시글을 초기화 하는 로직에서 로그인 정보 =true를 추가
> 상세 게시글에서 강력 새로고침 시 투표 인원수가 -1명으로 변하는 버그 수정

- frontend/src/components/common/Dashboard/CategorySection/style.ts
- frontend/src/pages/auth/Redirection.tsx
close: #358
close: #381
close: #384
- 카테고리가 스크롤 되도록 CSS 수정
- 엑세스 토큰이 없을 때 리다이렉션 페이지를 통해 로그인 시에도 멤버 아이디를 전역변수에 설정되도록 수정
30분
- 로그인 후 내가 작성한 글의 통계가 보이지 않거나, 상세 페이지에서 내가 작성한 글에 신고가 뜨는 이유가 리다이렉션 페이지에서 멤버 아이디를 전역 변수로 설정
- 카테고리가 길 경우 스크롤 되도록 CSS 설정
-  헤더, 유저인포, 로그아웃 버튼 등의 높이값을 계산하여서 스크롤 되는 높이를 100vh - 400px(유저 정보창 + 헤더창 + 선택된 게시글 종류 + 로그아웃 버튼) 으로 지정
카테고리 스크롤 동영상
https://github.com/woowacourse-teams/2023-votogether/assets/80146176/69fe4acf-6ff6-426f-8508-9528b19c41a2
> 카테고리가 길 경우 스크롤이 되도록 변경, 리다이렉션 페이지에서 멤버 아이디를 설정하도록 수정

- frontend/src/api/post.ts
- frontend/src/api/report.ts
- frontend/src/components/PostForm/ContentImageSection/index.tsx
- frontend/src/hooks/useContentImage.ts
close: # 280 (보류)
close: #391
본문과 내용에 사진을 추가할 때 안될 때가 있다
1시간.. 해결 못함..
문제 설명
- 이미지 업로드 (changeEvent) > 이미지 삭제 (state로 관리하는 url만 삭제 - 미리보기 삭제) > 이미지 업로드 (changeEvent) 시 동일한 파일이라 changeEvent 발생하지 않음
- 때문에 본문 이미지 문제 해결을 위해 ref로 이미지 삭제시 해당 input.value를 ""처리 
- 선택지는 ref를 html[]로 만드려고 했는데 계속 null값이 나오며 element가 지정되지 않음..
일단 문제점과 해결책을 알았으니 다음 기회에 개선하면 좋을 것 같습니다.
배포가 더 중요하다고 생각되어 PR올립니다.
> 본문과 내용에 사진을 추가할 때 안될 때가 있다

- frontend/src/components/common/Post/index.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/WrittenVoteOption.stories.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/index.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOptionList.stories.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/index.tsx
- frontend/src/pages/VoteStatisticsPage/OptionStatistics/index.tsx
close: #399 
- 회원이 마감 완료된 게시글에 투표할 때 '마감된 게시글에는 투표를 할 수 없습니다.' 라는 토스트를 보여줌
- 마감 완료된 게시글은 투표 통계가 보이도록 수정
20분
- 기존에 투표 통계가 보이도록 하는 isVoted와 isWriter를 좀 더 넓은 범위라고 생각되는 isStatisticsVisible(통계가 보이는 지)로 변경
- 마감 시간이 지난 게시글에 투표했을 때 토스트가 올라오는 이미지
문구가 적당한가요? 아니면 마감 시간이 지난 게시글을 투표했을 때 바로 return해서 토스트가 안 나오는 것도 괜찮은지 논의해보고 싶어요
> 회원이 마감 완료된 게시글에 투표할 때 failed to Fetch가 나타나요, 마감된 게시글 투표 통계 보이도록 수정

- frontend/src/components/common/NarrowMainHeader/index.tsx
- frontend/src/components/common/SearchBar/index.tsx
- frontend/src/components/post/PostListPage/style.ts
close: #403 
- 검색창을 눌러도 검색창이 안닫히도록 수정
- 모바일에서 검색창 열었을 때 오토포커스 되도록 구현
- 홈페이지에서 위로가기, 작성 버튼에 padding-right:10px 추가 ( 너무 붙어있어서 )
20분
동영상
https://github.com/woowacourse-teams/2023-votogether/assets/80146176/1c7e76f0-4873-41e2-8641-52e8e296bf46
> 모바일에서 검색창 눌러서 검색이 가능하도록 수정

- backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
- backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
- backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
- backend/src/test/java/com/votogether/domain/post/repository/CommentRepositoryTest.java
- backend/src/test/java/com/votogether/domain/report/service/ReportServiceTest.java
close: #438 
게시글과 댓글이 신고 5번 이상이어도 보이는 버그 픽스
30분
게시글과 댓글이 신고 5번 이상이어도 보이는 상황에서 안보이도록 수정
> 게시글과 댓글이 신고 5번 이상이어도 보이는 버그 픽스

- frontend/src/components/comment/CommentList/index.tsx
- frontend/src/components/common/ScrollToTop/index.tsx
- frontend/src/components/post/PostListPage/index.tsx
- frontend/src/pages/post/CreatePostPage/index.tsx
- frontend/src/pages/post/EditPostPage/EditPost/index.tsx
- frontend/src/routes/router.tsx
- frontend/src/utils/scrollToTop.ts
close: #419 
글을 작성하면 리스트 정렬기준이 "최신순"으로 바뀌었으면 좋겠어요 
close: #423 
내가 작성한 게시물/투표한 게시물/홈으로 이동할때 최상단으로 이동되지 않아요
- 글 작성/수정 시 글 목록 정렬/필터링 기준 초기화
- 페이지 이동 시 최상단으로 이동(상세게시물에서 목록으로 이동할때는 제외)
2시간
- window.scroll이 작동하지 않는 오류
- 글 작성/수정 시 글 목록 정렬/필터링 기준 초기화
- 페이지 이동 시 최상단으로 이동(상세게시물에서 목록으로 이동할때는 제외)
- 유틸로 페이지 이동 관련 함수를 분리
- 컴포넌트로 페이지 이동 컴포넌트를 만듦
- 라우터에 스크롤 컴포넌트 적용
- 스크롤 컴포넌트가 각 페이지마다 있어서 많이 사용되고 있습니다. 사실 그럴 필요 없이 라우터스에 바로 정의해도 작동되는데 지금 저희가 라우터 크리에이트.. 로 라우터를 정의하고 있어서 해당 방식에는 어떻게 스크롤 컴포넌트를 넣을 수 있을지 몰라 지금 방식을 채택했습니다. 단 한번만 넣어도 된다고 생각되어 방법을 찾으면 리팩토링 하고 싶습니다.
- 왜... 스크롤이 적용되고 적용되지 않는지 모르겠습니다. 아직도 잘 모르겠어요.. 상세페이지에서 리스트로 넘어가는 부분을 조건문으로 확인하려고 했는데 useRef로 하는 방식이 문제가 있어서 일단 삭제했습니다. 없어도 의도대로 돌아가긴 해서 추후 문제가 생겼을때 보완하면 좋을 것 같아요.
> 글을 작성하면 리스트 정렬기준이 "최신순"으로 바꾸기, 라우팅 시 스크롤 최상단으로 이동하기

- backend/src/main/java/com/votogether/domain/post/entity/Post.java
- backend/src/main/java/com/votogether/domain/post/entity/PostOptions.java
- backend/src/main/java/com/votogether/domain/post/service/PostService.java
close: #448 
게시글 수정 시, PostOption 테이블 유니크 값 충돌 문제 해결
5시간
게시글 수정 시, PostOption 테이블 유니크 값 충돌 문제 해결
> 게시글 수정 시, PostOption 테이블 유니크 값 충돌 문제 해결

- frontend/src/components/comment/CommentList/CommentItem/index.tsx
- frontend/src/components/comment/CommentList/CommentItem/style.ts
- frontend/src/components/common/LogoButton/index.tsx
- frontend/src/components/common/NarrowMainHeader/index.tsx
- frontend/src/components/common/NarrowMainHeader/style.ts
- frontend/src/components/common/SearchBar/index.tsx
- frontend/src/components/common/SearchBar/style.ts
- frontend/src/components/common/Select/index.tsx
- frontend/src/components/common/Select/style.ts
- frontend/src/components/common/Skeleton/index.tsx
- frontend/src/components/post/PostList/index.tsx
- frontend/src/hooks/query/user/useModifyUser.ts
- frontend/src/pages/MyInfo/index.tsx
- frontend/src/pages/post/PostDetail/PostDetail/index.tsx
- frontend/src/styles/globalStyle.ts
close: #349 
close: #407 
* 닉네임 변경 및 신고 API 통신 실패 시 백엔드에서 주는 에러 메시지를 Toast로 띄웁니다.
* NarrowMainHeader, Select, Searchbar, Skeleton 컴포넌트 웹접근성 개선
* 4시간 
* aria-label, aria-live 속성을 이용하여 웹접근성을 개선하였습니다.
* 모바일 안드로이드로 테스트하여서 데스크탑도 잘되는지 장담할 수 없습니다..😅🤔
> NarrowMainHeader, Select, Searchbar, Skeleton 컴포넌트 웹접근성 개선 / 닉네임 변경 및 신고 API 실패 시 Toast 띄우기

- frontend/src/components/PostForm/ContentImageSection/index.tsx
- frontend/src/components/common/Post/index.tsx
- frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/index.tsx
- frontend/src/pages/Error/index.tsx
- frontend/src/pages/MyInfo/index.tsx
- 기본 이벤트로 인한 호출 오류
close: #468
close: #467
모바일/데스크탑에서 사진 업로드 버튼 클릭시 2번씩 파일 창이 뜨는 오류 수정 
사용자에게 보여지는 메세지 수정
5분
- 웹접근성 도입으로 button을 이용하여 file 업로드 창을 띄우도록 수정됨
- 이 과정에서 button이벤트와 중복되어 문제 발생
- button의 이벤트를 ```e.preventDefault();```로 막아 해결
- 닉네임 변경 주기 제한 안내 삭제
- 잘못된 보투게터 이메일 수정
> [BUG] 모바일/데스크탑에서 사진을 2번씩 눌러야 이미지 첨부가 돼요

- frontend/src/components/common/TimePickerOptionList/TimePickerOption/constants.ts
- frontend/src/components/common/TimePickerOptionList/TimePickerOption/index.tsx
- frontend/src/components/common/TimePickerOptionList/index.tsx
close: #456 
- 타임 픽커 웹 접근성 향상
- SquareButton, TagButton 은 aria-label을 사용하는 곳에서 작성하면 되기에 수정 X
20분
처음 포커스되었을 때는    aria-label={`현재 선택된 ${TIME_KOREAN[option]}은 ${currentTime} 입니다. 위, 아래 방향키 혹은 터치로 시간 조절이 가능합니다.`} 로 알려주고 
유저가 시간을 바꿀 때에는 현재 일, 시간, 분은 몇이다 라고  알려줍니다
> 타임 픽커 웹 접근성 향상

- .github/workflows/backend-pr-comment.yml
- .github/workflows/backend-pr-deadline-slack-bot.yml
- .github/workflows/frontend-pr-comment.yml
- .github/workflows/frontend-pr-deadline-slack-bot.yml
- .github/workflows/frontend-storybook-deploy.yml
- frontend/src/App.tsx
- frontend/src/components/PostForm/index.tsx
- frontend/src/components/common/Toast/style.ts
- frontend/src/components/post/PostListPage/style.ts
- frontend/src/hooks/query/user/useUpdateUserInfo.ts
- frontend/src/pages/VoteStatisticsPage/index.tsx
- frontend/src/pages/post/PostDetail/InnerHeaderPart/index.tsx
- frontend/src/pages/user/RegisterPersonalInfo/index.tsx
close: #474 
close: #476 
close: #477 
close: #478 
close: #518
* Toast 컴포넌트가 열리면 Toast 외부 화면을 눌러도 상호작용 되도록 style 수정함.
* 헤더의 뒤로가기 버튼누르면 홈이 아닌 바로 이전 url로 이동하도록 함
* 개인정보 최초 등록 후 다시 등록 페이지로 갈 수 없도록 라우팅 제한함
* UpButton, AddButton style 수정함
* 5시간
* 사이드바에서 토스트 잘려서 보이는거 해결하고 싶은데 왜 해결이 안될까요... z-index 쓰면 해결될 줄 알았는데 실패.. ㅜㅜ  (#475)
> 컴포넌트 사용성 개선 및 라우팅 제한 추가, github action worflow 오류 해결 등 버그 5건 수정 

- frontend/src/api/ranking.ts
- frontend/src/hooks/query/ranking/usePassionUserRanking.ts
- frontend/src/hooks/query/ranking/usePopularPostRanking.ts
- frontend/src/hooks/query/ranking/useUserRanking.ts
- frontend/src/mocks/handlers.ts
- frontend/src/mocks/ranking.ts
- frontend/src/pages/Ranking/PassionUser/PassionUser.stories.tsx
- frontend/src/pages/Ranking/PassionUser/UserRanking/index.tsx
- frontend/src/pages/Ranking/PassionUser/index.tsx
- frontend/src/pages/Ranking/PassionUser/style.ts
- frontend/src/pages/Ranking/PopularPost/PopularPost.stories.tsx
- frontend/src/pages/Ranking/PopularPost/index.tsx
- frontend/src/pages/Ranking/RankingTableStyle.ts
- frontend/src/pages/Ranking/index.tsx
- frontend/src/types/ranking.ts
close: #521
1시간
: 연결할게 많을 줄 알았는데 기존 코드를 따라했더니 얼마 안걸리네요.
- 기존 방식대로 서스펜스, 에러바운더리 적용했습니다.
- 이전 pr에서는 랭킹 페이지에서 api를 불러오는 것으로 생각했는데 막상 서스펜트, 에러바운더리를 적용하려고 하니까 불필요하게 내려받는 과정이 생기는 것 같아 랭킹 테이블(열정유저, 인기글)에서 바로 api를 받는 것으로 수정했습니다.
- 열정유저 테이블에서 사용자 랭킹은 따로 분리하여 서스펜스와 에러바운더리를 적용했습니다. 때문에 아래와 같이 처리됩니다. 이는 서스펜스도 동일합니다. 열정유저와 사용자 랭킹을 아예 분리하는 것도 고려하였으나 현재 css 코드로는 테이블의 12번째 행에 사용자랭킹 UI처리가 되어있어 처리하기 어려운 부분도 있고, 열정 랭킹 내에 사용자 (열정) 랭킹이 포함된다고 생각이 들어 아래처럼 처리했습니다. 의견 있으시면 말씀주세요!
1. 열정유저 api는 성공하고 사용자 랭킹 api는 실패한다 > 사용자 랭킹 부분만 에러 바운더리 적용 
2. 열정유저 api는 실패하고 사용자 랭킹 api는 성공한다 > 열정유저 랭킹 테이블 전체가 에러 바운더리 적용
- 기존 코드에 허점이 있었습니다..
- 사용자랭킹 쿼리훅 이름이 수정되지 않아 열정랭킹 쿼리훅과 동일했습니다 > 수정완료
- 열정유저 랭킹, 인기글 랭킹 type이 배열로 되어있지 않았습니다 > 수정완료
- 현재 msw 적용 완료입니다.
https://github.com/woowacourse-teams/2023-votogether/assets/113416448/9eb88a04-b97 …
> 랭킹 UI와 hook 연결 및 msw 도입 (+변경된 랭킹 객체 타입 적용) 

- frontend/src/constants/policyMessage.ts
- frontend/src/index.tsx
- frontend/src/pages/MyInfo/index.tsx
close: #528 
- 닉네임 정책 사용자에게 14일마다 가능하다고 안내 메세지 변경
- 닉네임 정책 온전한 한글만 닉네임 변경이 가능하다고 메세지 추가
- 권장되지 않는 코드 삭제 ( #484 )
10분
> 닉네임 정책 사용자에게 14일마다 가능하다고 안내 메세지 변경

- backend/src/main/java/com/votogether/domain/member/entity/Member.java
- backend/src/main/java/com/votogether/domain/member/entity/vo/Nickname.java
- backend/src/main/java/com/votogether/domain/member/exception/MemberExceptionType.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
- backend/src/test/java/com/votogether/domain/member/entity/MemberTest.java
- backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
close: #491 
초기에 랜덤닉네임이 지정된 후에 1회는 자유롭게 변경이 가능합니다.
1회 변경 후에는 최소 14일이 지나야 닉네임을 변경할 수 있도록 로직을 추가하겠습니다.
1시간 
없음.
없음.
> 회원의 닉네임을 일정주기를 통해 변경할 수 있도록 구현

- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.common.js
close: #561
* `webpack-bundle-analyzer` 플러그인을 삭제함.
* 10분
* `webpack-bundle-analyzer` 플러그인을 사용하면 `http://127.0.0.1:8008` 에서 번들 사이즈를 확인하도록 하는데, 8008 포트가 계속 열려있으면 build 가 성공적으로 끝나지 않음..
* 해당 플러그인은 개발 중 번들 사이즈를 확인하기 위함이며, 프로덕션에서는 불필요하므로 삭제함.
> 불필요한 플러그인(webpack-bundle-analyzer) 삭제하여 github action 무한 로딩 해결

- frontend/__test__/getSelectedState.test.ts
- frontend/__test__/getTrimmedWord.test.ts
- frontend/__test__/hooks/useSearch.test.tsx
- frontend/__test__/hooks/useSelect.test.tsx
- frontend/src/components/common/Dashboard/CategorySection/index.tsx
- frontend/src/components/common/SearchBar/index.tsx
- frontend/src/hooks/context/postOption.tsx
- frontend/src/hooks/useCurrentKeyword.ts
- frontend/src/hooks/usePostRequestInfo.ts
- frontend/src/hooks/useSearch.ts
- frontend/src/hooks/useText.ts
- frontend/src/utils/getTrimmedWord.ts
- frontend/src/utils/post/getSelectedState.ts
close: #530 
close: #534 
- 검색할 때 아무런 값이 없으면 검색되지 않도록 하기, 검색어 남기기, 앞 뒤 trim ()처리 하기 등 
- 페이지 진입 시 전체, 최신순으로 정렬 옵션이 설정되도록 수정
- 왼쪽 사이드바에서 검색어가 나오던 기능 삭제
1시간
https://github.com/woowacourse-teams/2023-votogether/assets/80146176/9aafa44b-3421-471d-a172-33323c0c0ab3
> 검색에 관한 설정과 전체 게시글 초기 설정 변경

- backend/src/main/java/com/votogether/domain/post/controller/PostController.java
- backend/src/main/java/com/votogether/domain/post/controller/PostControllerDocs.java
- backend/src/main/java/com/votogether/domain/post/dto/response/post/PostCompactResponse.java
- backend/src/main/java/com/votogether/domain/post/dto/response/post/PostRankingResponse.java
- backend/src/main/java/com/votogether/domain/post/dto/response/post/PostSummaryResponse.java
- backend/src/main/java/com/votogether/domain/post/service/PostService.java
- backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
close: #539 
인기게시글 랭킹 목록 조회 기능을 구현했습니다.
3시간
집중력 저하 및 에너지 고갈 + 테스트코드 작성 고민
모든 게시글에 대해서 인기순으로 10개의 게시글을 순서대로 조회합니다.
> 인기게시글 랭킹 목록 조회 기능

- backend/src/main/java/com/votogether/domain/ranking/controller/RankingController.java
- backend/src/main/java/com/votogether/domain/ranking/controller/RankingControllerDocs.java
- backend/src/main/java/com/votogether/domain/ranking/dto/response/RankingResponse.java
- backend/src/main/java/com/votogether/domain/ranking/entity/PassionRankings.java
- backend/src/main/java/com/votogether/domain/ranking/service/RankingService.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/votogether/domain/ranking/controller/RankingControllerTest.java
- backend/src/test/java/com/votogether/domain/ranking/service/RankingServiceTest.java
close: #565 
기존에 있던 메서드를 재활용하여 열정 유저 랭킹 목록 조회 기능을 구현했습니다.
2시간
없음.
부족한 테스트는 리팩터링하면서 추가해야할 것 같아요.
> 열정 유저 랭킹 목록 조회 기능

- frontend/public/index.html
close: #552 
- 네이버에서 소유 확인을 할 때 필요한 head의 meta 등록
10분
구글은 몇시간 기다려야 진행 가능할 것 같아요
1. SEO 설정했던 방법은 팀 블로그에 글 작성 후 공유하겠습니다
2. 해당 meta가 main으로 머지가 되어서 운영서버에서 meta가 있는지 네이버 측에서 확인을 한 후에 진행을 할 수 있습니다~
> 네이버 소유권 확인용 meta 설정

- frontend/src/api/ranking.ts
- frontend/src/pages/Ranking/PassionUser/index.tsx
close: #573
msw였던 것을 랭킹 api로 연결하기
1시간
다른 브랜치 작업과 동시에 작업
- msw였던 것을 랭킹 api로 연결하기
- 10명 이하 데이터가 불러와지는 경우 빈 행으로 처리
없습니다!
> 랭킹 api 연결하기

- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/src/App.tsx
- frontend/src/components/GoogleTagManager/index.tsx
- frontend/src/components/common/Drawer/style.ts
close: #592 
close: #475 
구글 태그 인식을 위한 script 코드 추가
10분
~~기존 코드로 구글 태그가 인식되지 않아 script를 추가함.~~
React 같은 SPA 앱인 경우에는 일반 html 문서와 렌더링 방식이 다르기 때문에, 컴포넌트를 별도로 만들어서 App.tsx 에서 import 해야 제대로 구글 태그가 인식된다고 하네요..!
이를 위해 `react-gtm-module`이라는 모듈 설치해줬습니다.
참고자료는 아래와 같습니다.
https://neep305.tistory.com/61
https://juunone.netlify.app/web/gtm/
https://goo-gy.github.io/2021-04-28-google-tag-manager
> 구글 태그 인식을 위한 script 코드 추가, 사이드바에서 Toast가 잘려 보이는 이슈 해결

- frontend/src/api/auth.ts
- frontend/src/pages/auth/Redirection.tsx
- frontend/src/utils/fetch.ts
close: #598 
- 로그인 시 getFetch를 할 때 credentials 설정을 추가해주었습니다
10분
> 로그인 시 쿠키를 주고 받을 수 있도록 fetch 설정 변경

- backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
- backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
close: #608 
- cookie에 path를 `/auth`에서 `/`로 변경했습니다.
- 레디스에서 RefreshToken의 TTL을 14일로 설정했습니다.
1분
`/auth`로 경로를 설정하게 되면 새로고침 시 쿠키가 삭제됩니다.
다른 경로에서 한번 받아오는 것은 되지만 그 이후에는 새로고침을 하면서 경로가 다르다고 판단하여 삭제하는 것 같아요.
`/`로 설정해야 새로고침을 해도 쿠키가 남아있습니다.
없음.
> cookie의 path를 /auth에서 /로 변경 및 RefreshToken TTL설정

- frontend/package.json
- frontend/src/hooks/useContentImage.ts
- frontend/src/hooks/useWritingOption.tsx
- frontend/src/utils/resizeImage.ts
close: #555 
- 게시글 작성 시 이미지 파일을 보낼 때 webp 로 압축하여 성능 개선
- 게시글 본문 적용
- 게시글 옵션 적용
- 2시간 (비슷한 내용의 패키지를 비교 분석하느라고 좀 늦어졌습니다)
- 확장자는 webp로 바꾸고, 사이즈는 1280으로 고정시켰습니다. 
이미지 압축 패키지 비교
https://husky-dodo-c5e.notion.site/555902772db5412ba9089737c56a2302?pvs=4
> 게시글 작성 시 이미지 파일을 보낼 때 webp 로 압축하여 성능 개선

- frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/OptionUploadImageButton/style.ts
- frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/style.ts
close: #622 
- 선택지가 왼쪽으로 움직이지 않도록 숨겨져있는 파일 인풋을 왼쪽으로 옮겨서 에러 메세지도 왼쪽에서 나타나도록 수정
20분
https://github.com/woowacourse-teams/2023-votogether/assets/80146176/a9e7be17-f1be-40a3-941e-8a078b12c79e
https://github.com/woowacourse-teams/2023-votogether/assets/80146176/dcd3947c-7f15-4e8a-80e4-7e6925dfae74
https://github.com/woowacourse-teams/2023-votogether/assets/80146176/a073ea21-f2ee-43e7-ac68-5bc5ef3be82a
참고자료
에러 메세지는 스타일링이 따로 안된다고 하네요~
https://stackoverflow.com/questions/67161694/html-default-validation-messages-styling
> 선택지가 왼쪽으로 움직이는 버그 수정

- frontend/src/components/PostForm/index.tsx
- frontend/src/hooks/useContentImage.ts
- frontend/src/hooks/useWritingOption.tsx
- frontend/src/utils/post/uploadImage.ts
close: #602 
- 본문 이미지 복사 붙혀넣기로 동작되도록 구현
- 중복되는 코드 분리 후 useContentImage, useWritingOption에서 import하여 사용
40분
- onPaste 이벤트에서 file의 타입이 image라면 이미지 파일을 붙혀넣기한 것으로 판단하고 업로드 input에 파일을 넣어주도록 구현
- 선택지와 본문에서 이미지 업로드 하는 코드가 중복된다고 생각하여 분리하였음
- 붙혀넣기 기능은 선택지는 미적용, 본문만 적용하였습니다. 그 이유는 useWritingOption에서 업로드 버튼의 ref가 필요한데 수아의 PR이 머지된 후 진행하는 것이 깔끔하다고 생각했습니다
https://github.com/woowacourse-teams/2023-votogether/assets/80146176/00b41419-e3cd-4f68-a140-62e06268126b
> 게시글 작성 시 이미지 복사 붙혀넣기로 이미지 첨부 가능하도록 구현

- frontend/package-lock.json
- frontend/src/hooks/query/category/useCategoryFavoriteToggle.ts
close: #563 
* 카테고리 즐겨찾기에 대한 낙관적 업데이트를 구현하였습니다.
* 8시간 
* fast 3g, slow 3g 환경에서도 UI 먼저 수정하도록 하되, 서버와의 통신에서 실패가 일어나면 이전 상태로 롤백하도록 하였습니다.
* 투표 수정에 대한 낙관적 업데이트 역시 시도했지만, 사용성 면에서 큰 의미가 없다고 판단하여 삭제하였습니다,,
(데일리에서 논의했듯, 선택지에서 `1명(100%)` 같은 정보는 서버 응답으로 제공하는 것입니다. 따라서 이런 수학적인 부분까지 낙관적 업데이트를 하고자 한다면, 이를 프론트가 미리 계산하기 위한 로직을 별도로 작성해야 합니다. 또한 `1명(100%)` 같은 정보를 제외하고, 그저 선택했는지 border 색깔만 바꿔서 보여준다면.. 결국 `1명(100%)` 정보는 나중에 볼 수 있으므로, 사용성 면에서 당황스럽고 불편할 수 있다고 생각합니다. 
이러한 이유로 투표 선택지 수정에 대한 낙관적 업데이트는 진행하지 않았습니다😂)
* 데일리에서 논의함.
> 카테고리 즐겨찾기에 대한 낙관적 업데이트 구현

- backend/src/main/java/com/votogether/domain/post/controller/PostGuestController.java
- backend/src/main/java/com/votogether/domain/post/controller/PostGuestControllerDocs.java
- backend/src/main/java/com/votogether/domain/post/dto/request/post/PostOptionCreateRequest.java
- backend/src/main/java/com/votogether/domain/post/dto/response/post/PostOptionVoteResultResponse.java
- backend/src/main/java/com/votogether/domain/post/entity/Post.java
- backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
- backend/src/main/java/com/votogether/domain/post/service/PostGuestService.java
- backend/src/main/java/com/votogether/infra/image/ImageName.java
- backend/src/main/java/com/votogether/infra/image/LocalUploader.java
- backend/src/test/java/com/votogether/domain/post/controller/PostGuestControllerTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostGuestServiceTest.java
- backend/src/test/java/com/votogether/domain/post/service/PostQueryServiceTest.java
- backend/src/test/java/com/votogether/infra/image/LocalUploaderTest.java
* close: #642
게시글 이미지 저장 버그를 수정하였습니다.
10분
1. 게시글 이미지 저장 버그를 수정하였습니다.
2. 사라졌던 인기 게시글 랭킹 조회 API 복원했습니다.
컨플릭트 해결 힘들어요 :(
> [BUG] 게시글 이미지 저장이 되지 않는 문제

- frontend/src/utils/token/silentLogin.ts
로그인 페이지로 보내지 않게 설정하기, 에러 로그 보기 위해서
close: #656 
- 리프레시 토큰 중복된 요청 보내지 않도록 하기
- 네트워크 탭 확인을 위해 실패했을 때 로그인 페이지로 보내는 코드 주석 처리
5분
> 리프레시 토큰 중복된 요청 보내지 않도록 하기

- frontend/src/components/post/PostList/index.tsx
- frontend/src/components/post/PostList/style.ts
close: #639 
close: #640 
- [무한스크롤 시 10번째 게시글 공백이 다른 문제 수정](https://github.com/woowacourse-teams/2023-votogether/commit/28b9061f0e44c993e7dd798617a8511d6a87d035)
- [무한 스크롤 시 일부 게시글의 border이 없던 문제 해결](https://github.com/woowacourse-teams/2023-votogether/commit/9347ecd8347dca3ae933c59fcce7f932cfb805fd)
30분
CSS 속성을 통해 해당 문제들을 해결했습니다
> 게시글 리스트에서 CSS 다르게 보이는 문제 해결

- frontend/package-lock.json
- frontend/src/components/ChannelTalk/index.tsx
- frontend/src/components/common/AppInstallPrompt/BookMarkPrompt/style.ts
- frontend/src/components/common/AppInstallPrompt/index.tsx
- frontend/src/components/common/Layout/index.tsx
- frontend/src/pages/Ranking/index.tsx
close: #595 
close: #609 
* 앱설치 프롬프트 하단이 채널톡에 가려지는 버그를 수정함.
* 랭킹페이지의 내랭킹이 채널톡에 가려지는 버그를 수정함.
* 2시간
* 채널톡의 `hideChannelButton`, `showChannelButton` 이라는 함수들을 활용했습니다.
* 랭킹 페이지에서는 채널톡 버튼을 가렸습니다.
* 앱설치 프롬프트가 열려있는 경우 채널톡 버튼을 가리고, 프롬프트 창을 닫으면 채널톡 버튼이 보이게 했습니다.
* 앱설치 프롬프트가 Iphone SE와 Galaxy Fold 같은 너비가 작은 디바이스에서는 폰트 사이즈 등의 스타일을 조정하였습니다.
없음.
> 채널톡이 앱설치 프롬프트와 랭킹 페이지의 내랭킹을 가리는 버그 수정

- frontend/src/components/common/InputNSubmitButton/index.tsx
- frontend/src/components/common/InputNSubmitButton/style.ts
- frontend/src/components/common/Post/index.tsx
- frontend/src/constants/user.ts
- frontend/src/pages/MyInfo/index.tsx
- frontend/src/pages/MyInfo/style.ts
- frontend/src/pages/Ranking/PageContent/index.tsx
- frontend/src/pages/Ranking/index.tsx
close: #650 
React.memo를 이용해 새로운 게시글 불러올 때 기존 데이터 리렌더링 하지 않기 
3시간
: 지료를 찾아본 시간이 길고, 상태를 확인하는 시간이 길었음
1. 작업한 내용 
-  새로운 게시글 불러올 때 기존 데이터 리렌더링 하지 않기
- React.memo를 이용하여 post 컴포넌트를 감쌈
2. 작업하지 않은 내용 + 이유
-  랭킹 페이지 토글 전환 시 레이아웃 리렌더링하지 않기
- 페이지에서 상태를 가지고 있는데, 이를 분리하거나 라우터로 레이아웃을 옮겨야지만 리렌더링을 해결 할 수 있음
- 분리한다면 불필요한 레이어가 하나 더 씌인다고 생각됨
- 라우터로 레이아웃을 옮기면 다른 페이지와의 통일성이 없음. 그렇다고 모든 페이지의 레이아웃을 라우터로 옮기는 것도 과하다고 생각됨.
- 리렌더링을 줄이는 것보다 코드변경에 드는 비용이 더 크다고 생각되어 수정하지 않음
-  댓글 작성하는 경우 저장 버튼과 다른 댓글들 리렌더링 하지 않기
-  닉네임 변경 input에서 changeEvent 발생시 input 제외하고 리렌더링 하지 않기
-   게시글 작성 폼에서 input 작성 시 모든 폼 태그가 리렌더링되지 않게 하기
- 위 세가지는 동일한 문제인데, 작성할 때 changeEvent로 제어하기 때문에 state가 변경되어 관련된 컴포넌트가 렌더링되는 문제점을 가지고 있음. 이를 해결하기 위해서는 비제어컴포넌트로 변경해야 함. 디바운스를 고려해보기도 하였으나 그러면 content가 사용자 눈에는 버벅이며 입력될 것으로 예상되어 기각함. 위와 마찬가지로 렌더링을 위해 제어를 비제어로 …
> useMemo/useCallback/React.memo를 사용하여 최적화하기

- frontend/src/components/PostForm/PostForm.stories.tsx
- frontend/src/components/PostForm/index.tsx
- frontend/src/components/ReportModal/ReportModal.stories.tsx
- frontend/src/components/ReportModal/index.tsx
- frontend/src/components/comment/CommentList/CommentItem/index.tsx
- frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
- frontend/src/components/common/DeleteModal/DeleteModal.stories.tsx
- frontend/src/components/common/DeleteModal/index.tsx
- frontend/src/components/common/HeaderTextButton/index.tsx
- frontend/src/components/common/HeaderTextButton/style.ts
- frontend/src/components/common/Post/index.tsx
- frontend/src/hooks/query/post/useDeletePost.ts
- frontend/src/pages/post/CreatePostPage/index.tsx
- frontend/src/pages/post/EditPostPage/EditPost/index.tsx
- frontend/src/pages/post/PostDetail/BottomButtonPart/BottomButtonPart.stories.tsx
- frontend/src/pages/post/PostDetail/BottomButtonPart/index.tsx
- frontend/src/pages/post/PostDetail/InnerHeaderPart/InnerHeaderPart.stories.tsx
- frontend/src/pages/post/PostDetail/InnerHeaderPart/index.tsx
- frontend/src/pages/post/PostDetail/PostDetail/index.tsx
- frontend/src/pages/post/PostDetail/types.ts
close: #473
close: #611
close: #646 
close: #648 
* 마감된 게시글에 투표하는 경우 code 등 불필요한 정보까지 Toast에 뜨지 않도록 에러 메시지를 가공했습니다.
* 삭제된 게시글에 투표하는 경우에도 마찬가지로, message만 Toast에 뜨도록 하였습니다. (현재 `알 수 없는 서버 에러입니다` 라는 이슈는 #658 에서 해결 중입니다!)
* 댓글에 빈 문자열이나 공백, 개행만 입력하고 저장하는 것을 방지하였습니다.
* 기존의 Mutation이 로딩 중인데, 중복으로 Mutation 하는 경우를 방지하였습니다.
* 기존의 Mutation이 로딩 중이라면, SquareButton이 gray이고 disabled 되도록 하였습니다.
4시간
useMutation이 사용되는 기능은 아래와 같습니다. (✅는 이 pr에서 적용한 부분입니다.)
- 댓글 생성/수정 (POST/PATCH) ✅
- 댓글 삭제 (DELETE) ✅ -> DeleteModal이 열고 닫히는 텀이 있음 (이벤트 핸들러만 작동 못하게 제어할 것)
- 게시글 생성/수정 (POST/PATCH) ✅
- 게시글 삭제 (DELETE) ✅ -> DeleteModal이 열고 닫히는 텀이 있음 (이벤트 핸들러만 작동 못하게 제어할 것, 단 데스크탑에서는 '게시글 삭제' 버튼이 disabled, 회색으로 되도록 함)
---
남은 기능 중 Mutation은 아래와 같습니다.
- 닉네임 변경 (PUT) 
- 개인정보 등록 (POST) 
- 탈퇴 (DELETE)
- 투표 생성 (POST) 
- 투표 수정 (PATCH) 
- …
> 댓글 및 게시글에 대한 중복 Mutation 방지 처리, 가공된 에러 메시지를 Toast로 띄우도록 수정

- frontend/__test__/calculateAspectRatioSize.test.ts
- frontend/jest.setup.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/hooks/useContentImage.ts
- frontend/src/utils/calculateAspectRatioSize.ts
- frontend/src/utils/getImageSize.ts
- frontend/src/utils/resizeImage.ts
close: #683 
- 이미지 압축 패키지를 Browser Image Compression에서 upload-images-converter로 변경
- 이미지 너비, 높이를 반환하는 함수 구현
- 이미지 너비, 높이를 이미지 비율대로 재조정하여 반환하는 함수 구현
1시간
- upload-image-converter은 기존에 사용하던 패키지와 달리 이미지를 비율대로가 아닌 지정한 값으로 자르는 옵션만 설정할 수 있어서 직접 비율대로 자르기 위해 해당 함수를 구현
- jest에서 upload-image-converter을 인식하지 못해서 따로 jest.mock 하는 코드를 추가하였고, 이를 설명하는 주석을 추가했습니다
처리 속도 : 6ms
처리 속도: 20ms
####Browser Image Compression
크기: 55kb
크기: 5kb
> 이미지 압축 패키지를 Browser Image Compression에서 upload-images-converter로 변경

- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/ProgressBar/index.tsx
- frontend/src/components/optionList/WrittenVoteOptionList/WrittenVoteOption/ProgressBar/style.ts
- frontend/src/components/post/Post/index.tsx
- frontend/src/components/post/Post/style.ts
- frontend/src/components/post/PostList/index.tsx
- frontend/src/components/post/PostList/style.ts
close: #700 
라이트 하우스 웹 접근성 점수를93점에서 98점으로 올림
1시간
- forwardRef로 Post에서 ref를 받도록 하여 기존에 div -> li로 사용하던 코드 삭제
- 스타일드 컴포넌트 props에서 $를 안붙히고 사용하던 코드 수정
https://github.com/woowacourse-teams/2023-votogether/issues/700
웹 접근성에서 우리 색이 자꾸 대비가 낮다고 하는데 저는 무시하고 싶어요 얘네들이 권장하는 색까지 대비를 해보았더니 너무 안이쁘더라구요
https://dequeuniversity.com/rules/axe/4.7/color-contrast
> lightHouse 웹 접근성 93점을 98점으로 올렸음

- frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/WritingVoteOption.stories.tsx
- frontend/src/components/optionList/WritingVoteOptionList/WritingVoteOption/index.tsx
- frontend/src/components/optionList/WritingVoteOptionList/index.tsx
- frontend/src/hooks/useWritingOption.tsx
close: #675 
- 선택지에서 이미지 붙혀넣기로 업로드 가능하도록 구현
30분
전에 만들어 놓은  메서드를 활용해서 붙혀넣기를 가능하게 했음
```tsx
const setPreviewImageUrl = (optionId: number) => (imageUrl: string) => {
const updatedOptionList = optionList.map(optionItem => {
if (optionItem.id === optionId) {
return { ...optionItem, imageUrl };
}
return optionItem;
});
setOptionList(updatedOptionList);
};
```
> 선택지에서 이미지 붙혀넣기로 업로드 가능하도록 구현

- backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
- backend/src/test/java/com/votogether/domain/auth/service/AuthServiceTest.java
close: #688 
이전에 인프라 문제로 실패했던 테스트 컨테이너를 사용한 갱신 토큰에 대한 검증을 추가했습니다.
10분
없음.
없음.
> 테스트 컨테이너를 이용한 리프레시 토큰 검증 추가

- backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
* close: #716
CORS 에러를 해결하였습니다.
5분
`CorsRegistry`가 수행하던 설정을 `CorsFilter`에 동일하게 적용하였습니다.
> 왜 프록시 서버에서 걸러주지 않을까요?
실패한다면 `CorsRegistry` 다시 살리도록 하겠습니다 :(
> [BUG] CORS 에러 해결

- frontend/__test__/convertTextToUrl.test.ts
- frontend/src/components/PostForm/index.tsx
- frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
- frontend/src/components/post/Post/index.tsx
- frontend/src/components/post/Post/style.ts
- frontend/src/hooks/useText.ts
- frontend/src/utils/post/convertTextToElement.tsx
- frontend/src/utils/post/convertTextToUrl.ts
close: #703 
- 게시글 작성 시 본문 링크 삽입을 하지 않더라도 사용자에게 링크 클릭이 가능하도록 변경
2시간
- 본문 링크 삽입 시 [[ ]] 을 붙혀주고 있는데, 이걸 작성자에게 붙히도록 하지 않고 렌더링 시 http | https | www 로 시작하는 문자를 정규표현식을 이용하여 [[ 주소 ]]를 붙혀주도록 함
- 이 때 기존의 사용되던 [[ 링크 ]] 텍스트가 있다면 변환되지 않도록 하였음 
- 현재 홈에서 게시글 본문에 링크가 있다면 a 태그 내부에 a 태그가 있다는 에러가 나는데 본문에서 링크 렌더링 시 span으로 렌더되도록 수정
```
react-jsx-runtime.development.js:87 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Post`. See https://reactjs.org/link/warning-keys for more information.
```
```
react_devtools_backend_compact.js:13096 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
at a
```
https://github.com/woowacourse-teams/2023-votogether/assets/80146176/39254188-91a6-4758-9f51-2ee8d25df5d5
https://regex101.com/r/dVEb0X/1  (정규 표현식 테스트 …
> 게시글 작성 시 본문 링크 삽입을 하지 않더라도 사용자에게 링크 클릭이 가능하도록 변경

- frontend/src/components/PostForm/CategoryWrapper/index.tsx
- frontend/src/components/PostForm/index.tsx
- frontend/src/components/common/MultiSelect/index.tsx
- frontend/src/hooks/useMultiSelect.ts
close: #763
- 삭제된 addText가 포함된 PR이 머지되어 발생하는 오류 해결
- 토스트 미적용 부분 추가 적용(글쓸때 카테고리 4개이상 추가하려고 하면 alert 나옴)
10분
- 오류 발생 부분 addText코드 삭제
- 카테고리 훅 4개이상 추가 요청 시 토스트로 변경
- 3개 다 채우면 자동으로 다중셀렉터 닫기
- 4개 이상 하려고 하면 토스트 띄우고 다중셀렉터 닫기
> [BUG] 삭제된 addText가 포함된 PR이 머지되어 발생하는 오류 해결 

- frontend/src/components/AlarmContainer/ListStyle.ts
- frontend/src/components/common/NarrowMainHeader/style.ts
- frontend/src/components/common/WideHeader/index.tsx
- frontend/src/hooks/query/alarm/useReadAlarm.ts
- frontend/src/hooks/query/user/useReadLatestAlarm.ts
- frontend/src/pages/HomePage/index.tsx
close: #772
- 비회원일때는 알람을 요청하지 않음
- 비회원일 때 알람 버튼을 누르면 "로그인 하라는" 토스트 띄우기
- 모바일 홈 헤더 제위치로 돌려놓기
30분
- 비회원일때는 알람을 요청하지 않음
- 기존 코드: drawer 안에 알람 컨테이너가 있어 content 알림이 불림
- 수정 코드: drawer 안에서 로그인 여부를 확인해 비회원인 경우 알람 컨테이너를 그리지 않음
- 알람 컨테이너 안 리스트에 api 통신하는 로직 포함됨
- 비회원일 때 알람 버튼을 누르면 "로그인 하라는" 토스트 띄우기
- 알림을 읽는 patch api가 실패했을 때 토스트 안내 X
- 비회원일때 알림 버튼을 누르면 토스트 안내 O
- 모바일 홈 헤더 제위치로 돌려놓기
> [BUG] 알림이 비회원일때도 api요청을 해서 에러가 뜹니다

- backend/src/main/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepository.java
- backend/src/main/java/com/votogether/domain/alarm/service/AlarmQueryService.java
- backend/src/main/java/com/votogether/domain/member/service/MemberService.java
- backend/src/main/java/com/votogether/domain/notice/repository/NoticeRepository.java
- backend/src/main/resources/application.yml
- backend/src/test/java/com/votogether/domain/alarm/controller/AlarmQueryControllerTest.java
- backend/src/test/java/com/votogether/domain/alarm/repository/ReportActionAlarmRepositoryTest.java
- backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
- backend/src/test/resources/application.yml
close: #767 
- 신고 조치 관련 추가 피드백을 반영했습니다. (https://github.com/woowacourse-teams/2023-votogether/pull/756)
- 회원탈퇴시 신고조치알림과 공지사항을 삭제하는 로직을 추가하였습니다.
- 커넥션풀 관련 환경변수 추가하였습니다.
30분
Q. 이벤트리스너 테스트에서 @Disable 을 붙인 이유는 깃허브 액션때문에 추가하신건가요?
> 커넥션풀 관련 설정 추가 + 회원탈퇴시 fk 관련 삭제 로직 추가

- frontend/src/components/ReportModal/index.tsx
- frontend/src/components/comment/CommentList/CommentItem/index.tsx
- frontend/src/hooks/query/report/useReportAction.ts
- frontend/src/hooks/query/report/useReportContent.ts
- frontend/src/pages/post/PostDetailPage/BottomButtonPart/index.tsx
- frontend/src/pages/post/PostDetailPage/InnerHeaderPart/InnerHeaderPart.stories.tsx
- frontend/src/pages/post/PostDetailPage/InnerHeaderPart/index.tsx
- frontend/src/pages/post/PostDetailPage/PostDetail/index.tsx
close: #734
- 모바일에서 신고하려고 하면 로그인 후 이용하라고 안내 메세지 보이기
- 신고하기 api를 쿼리 훅으로 만들기
1시간
- 모바일에서 신고하려고 하면 로그인 후 이용하라고 안내 메세지 보이기
- 원래는 포스트 디테일 페이지에서 해주려고 했는데, 그럼 모달까지 다 선택하고 나서 요청을 거절하는 토스트가 나오게 되어 사용성을 저해한다고 생각
- 때문에 innerHeaderPart/bottomPart에서 action을 취하려고 할때 1차적으로 확인 후 토스트 안내를 내보내기로 결정
- 신고하기 api를 쿼리 훅으로 만들기
신고하기 mutate를 게시글/닉네임 같이 사용하는데 문제가 되진 않겠죠?
> [BUG] 모바일 비회원일 때 신고 버튼을 눌르면 알 수 없는 에러 메세지입니다라고 떠요

- frontend/src/api/alarm.ts
- frontend/src/components/AlarmContainer/ContentAlarmList/index.tsx
- frontend/src/components/AlarmContainer/ReportAlarmList/index.tsx
- frontend/src/hooks/query/alarm/useReadAlarm.ts
- frontend/src/mocks/mockData/alarm.ts
- frontend/src/styles/globalStyle.ts
- frontend/src/types/alarm.ts
close: #778
알림 읽기 api를 content와 report로 나눠서 보내야 해서 코드 수정
한번 읽은 알림은 다시 해당 api 안보내도록 처리
10분
- 알림 읽기 api를 content와 report로 나눠서 보내야 해서 코드 수정
-  기존 api
> /alarms/{id}
- 수정 api
> alarmType = “CONTENT” | “REPORT”
> /alarms/{id}?type={alarmType} 
아직 서버의 알림 api가 완성되지 않아서 api 완성되면 연결확인 되는 것까지 확인하고 머지하겠습니다!
> 알림 읽기 api를 content와 report로 분리함에 따라 코드 수정

- backend/src/main/java/com/votogether/domain/notice/dto/response/NoticeResponse.java
- backend/src/test/java/com/votogether/domain/notice/controller/NoticeQueryControllerTest.java
> @JsonFormat 추가

- backend/src/main/java/com/votogether/domain/alarm/dto/event/PostAlarmEvent.java
- backend/src/main/java/com/votogether/domain/alarm/dto/response/PostAlarmDetailResponse.java
- backend/src/main/java/com/votogether/domain/alarm/dto/response/PostAlarmResponse.java
- backend/src/main/java/com/votogether/domain/alarm/entity/Alarm.java
- backend/src/main/java/com/votogether/domain/alarm/service/AlarmEventListener.java
- backend/src/main/java/com/votogether/domain/alarm/service/AlarmQueryService.java
- backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
- backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
- backend/src/test/java/com/votogether/domain/alarm/service/AlarmCommandServiceTest.java
- backend/src/test/java/com/votogether/domain/alarm/service/AlarmEventListenerTest.java
- backend/src/test/java/com/votogether/test/persister/AlarmTestPersister.java
close: #798 
댓글 작성 시 알림에서 댓글 작성자가 나오지 않아 테이블에 필드를 추가하는 작업을 진행했습니다.
10분
> 댓글 작성 시 알림 추가 기능 버그 수정

- frontend/src/api/notice.ts
- frontend/src/hooks/query/notice/useCreateNotice.tsx
- frontend/src/hooks/query/notice/useDeleteNotice.tsx
- frontend/src/hooks/query/notice/useModifyNotice.tsx
- frontend/src/mocks/notice.ts
close: #801 
- 공지사항 생성, 수정, 삭제 후 캐시 초기화 로직 변경
5분
쿼리키의 첫번째 값이 공지사항이라면 전부 초기화하도록 했습니다
그 이유는 notice만 초기화 했을 때 수정,삭제 시 배너, 페이지를 사용하는 공지사항 리스트가 변하지 않을것 같아서요
> 공지사항 생성, 수정, 삭제 시 캐시 초기화 로직 변경
